### ISSUE TITLE
Database > firebaseArray uses private member functions

### ISSUE THREAD

**Issue by kmcnellis** [firebase/FirebaseUI-Android#902] opened 2017-09-11 19:24 UTC
* FirebaseUI version: 2.3.0

Its very hard to subclass the firebaseArray class (for the database recyclerview), due to the member functions being private, not protected (esp. getIndexForKey).  This is needed to implement custom functionality.

**Comment by Eragon29** [comment] 2017-09-11 19:26
There was just a Thread about that.
https://github.com/firebase/FirebaseUI-Android/pull/898#event-1243891847

**Comment by samtstern** [comment] 2017-09-11 20:02
@kmcnellis can you tell us more about the features you're trying to implement on top of `FirebaseArray`?  We are working (as @Eragon29 pointed out) to get some of this visibility stuff ironed out for `3.0`.

**Comment by SUPERCILEX** [comment] 2017-09-11 20:11
@kmcnellis Yeah, I'm actually leaning towards completely preventing inheritance. @samtstern convinced me to not make the Firebase arrays final for testing and mockability's sake, but all the methods are private and final where possible. I can't think of any scenario where using a wrapper couldn't do a better job.

Since you're asking about `getIndexForKey`, I'm guessing you're looking for custom sorting? That could easily be achieved with a wrapper object that extends `ObservableSnapshotArray`.

**Comment by bagintz** [comment] 2017-09-25 23:05
@SUPERCILEX Can you explain a little more how one would implement a wrapper object that extends ObservableSnapshotArray for custom sorting?  I am now running into this to :-/

**Comment by SUPERCILEX** [comment] 2017-09-25 23:26
@bagintz There are two options:
1. You can use our method of sorting with your own custom list of snapshots by simply copying the `getIndexForKey` method.
2. Or, since you're pulling data from different sources that's probably going to be difficult, so instead, you can use [`DiffUtil`](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) to asyncronously figure out the proper order of your items and then call the related notify metods once `DiffUtil` returns a set of operations to transform your existing list into your updated properly sorted list of snapshots.

But like I said in the other thread, the RTDB really isn't designed for this kind of stuff. Instead, you should duplicate your data so you can get everything in the right order all in one pretty query.

**Comment by bagintz** [comment] 2017-09-25 23:31
@SUPERCILEX 
Ok, I was trying to use a custom comparator on the ObservableSnapshotArray and that was not working. I would much prefer #2, but am a little unclear how it would work.  I updated the search index to use a single key to find items by user and status 

query_key = [uid]_[status]

Which let's me get the data with one query (which is how I "fixed" the issue I was having in the other thread).  But now I want to get that resultant list of items sorted by a date field that is in there.  How am I able to use the "filter" with my new query_key above and then add something that helps me sort by date.

Thanks for the tips!

**Comment by SUPERCILEX** [comment] 2017-09-25 23:35
For that, you can use `setValue(..., priority)` where the priority is a `long` timestamp and then use `orderByPriority()` on the `Query`. Or, I think `orderBy("timestamp")` would also work.

**Comment by bagintz** [comment] 2017-09-25 23:38
@SUPERCILEX ok, I will take a look, I thought I could only have 1 orderby, since I am using the orderByChild to query for my [query_key] ???  Thanks again

**Comment by SUPERCILEX** [comment] 2017-09-25 23:41
@bagintz Oh shoot, I didn't know you were using orderby for the query. Does `equalTo` not work? Otherwise, you'll have to use client side sorting as mentioned with `DiffUtil`.

**Comment by bagintz** [comment] 2017-09-25 23:44
ref.orderByChild('query_key').equalTo('[uid]_[status') works great to get me my 4 values, but they each have a startDate (and weren't entered into Firebase in the correct order).  

So I think client side is the way to go.  I haven't used DiffUtil, I will give it a shot and come back if I have any questions :)

**Comment by bagintz** [comment] 2017-09-26 00:04
@SUPERCILEX Ok, I think I can see how I can get there with DiffUtil, the problem is that my ArrayList that I am using to populate the Adapter is showing a size of 0 even though it shows the correct 4 cards in my view:

```
Query myRef = loansRef.orderByChild("query_key").equalTo(queryString);
ObservableSnapshotArray<Loan> myArray = new FirebaseArray<>(myRef, POJO.class);
adapter = new Adapter(myArray, R.layout.item, Adapter.ViewHolder.class);

```
Works fine, but if I try to get the size of myArray it shows 0, which doesn't let me do any sorting before sending the updated array to DiffUtil. Am I doing my wrapper object of snapshots wrong?

**Comment by bagintz** [comment] 2017-09-26 14:08
@SUPERCILEX OK!! I got it working with diffutil.  2 quick questions:
1) Would it be helpful to do some sort of small writeup on what I did for future folks, and where should that go?
2) The only place I can find to do the initial diffutil to sort is onDatachanged, but that seems very inefficient, not to mention a little "jarring" to have the list show up and sort visually in front of you.  Is there any other place in the FirebaseRecyclerAdapter that I can trigger the initial sort AFTER the mSnapshots has been populated, but before the initial view is created?

Thank you so much

**Comment by bagintz** [comment] 2017-09-26 16:10
@SUPERCILEX I think I am going to give up for now.  It seems the DiffUtil won't work since the FirebaseRecyclerAdapter's snapshots are immutable so the clear and addAll methods won't work.  This causes the list to "look" correct, but it does not update the true location for the Firebase listeners :( 

Let me know if you have any other ideas.

```
final SnapshotDiffCallback diffCallback = new SnapshotDiffCallback(this.mSnapshots, sortedSnapshots);
final DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(diffCallback);

// clear snapshots and add
this.mSnapshots.clear();
this.mSnapshots.addAll(sortedSnapshots);

diffResult.dispatchUpdatesTo(this); // calls adapter's notify methods after diff is computed
```

**Comment by SUPERCILEX** [comment] 2017-09-26 20:24
@bagintz You're not quite understanding what I mean by "wrapper object". I going to do a bit of whiteboard coding here so please bear with me:
```java
class MySortedSnapshots extends ObservableSnapshotArray<MyModel> {
    List<DataSnapshot> mSortedSnapshots = new ArrayList(); // Hold you sorted snapshots and return them in List#get(int)

    // Get your data with other FirebaseArrays, then calculate a diff and update the wrapper object
    void onNewUpdateRecieved() {
        FirebaseArray.addChangeEventListener ...

        Tasks.call(myAsyncExecutor, () -> DiffUtil.calculateDiff(...); ).addOnSuccessListener(result -> {
            result.dispatchUpdatesTo(new ListUpdateCallback() {
                @Override
                public void onInserted(int position, int count) {
                    notifyOnChildChanged(ChangeEventType.ADDED, ...);
                }
    
                @Override
                public void onRemoved(int position, int count) {
                    // ...
                }
    
                @Override
                public void onMoved(int fromPosition, int toPosition) {
                    // ...
                }
    
                @Override
                public void onChanged(int position, int count, Object payload) {
                    // ...
                }
            });
        }
    }
}
```

Do you see what I'm doing here? You're basically implementing your own `FirebaseArray` but using composition with other `FirebaseArray`s. You can have a look at the more complex [`FirebaseIndexArray`](https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java) to get a general idea of what you should be doing. Hope this helps! 😄

**Comment by bagintz** [comment] 2017-10-03 20:08
@SUPERCILEX 
https://firebase.googleblog.com/2017/10/cloud-firestore-for-rtdb-developers.html
Timely!  :) 👍

**Comment by SUPERCILEX** [comment] 2017-10-03 20:16
@bagintz Yes! I was in the alpha so it was _sooooo_ hard not to let something slip. 😄

**Comment by bagintz** [comment] 2017-10-03 20:17
Ha!  I am converting over form RTD to this now!  I think it will be worth it.

**Comment by SUPERCILEX** [comment] 2017-10-03 20:42
@bagintz Definitely is, trust me!

**Comment by SUPERCILEX** [comment] 2017-10-05 23:07
@samtstern I don't think we're ever going to make `getSnapshotForKey` public since that's a private implementation detail, so this issue can probably be closed.

**Comment by SUPERCILEX** [comment] 2017-10-09 00:40
@samtstern While you're on that issue closing spree, do you want to take a look at https://github.com/firebase/FirebaseUI-Android/issues/902#issuecomment-334616352, https://github.com/firebase/FirebaseUI-Android/issues/533#issuecomment-334615572, https://github.com/firebase/FirebaseUI-Android/issues/870#issuecomment-334615863, https://github.com/firebase/FirebaseUI-Android/issues/915#issuecomment-334616185?

**Comment by samtstern** [comment] 2017-10-09 02:44
@SUPERCILEX yes I agree we should close this issue.  @kmcnellis thanks for raising it, if you have more ideas for extensibility just let us know.

**Closed by samtstern** 2017-10-09 02:44 UTC
Labels: feature:database
