### ISSUE TITLE
App Crashed : java.lang.IndexOutOfBoundsException  : com.firebase.ui.auth.ui.phone.PhoneVerificationActivity

### ISSUE THREAD

**Issue by Kishanjvaghela** [firebase/FirebaseUI-Android#1097] opened 2018-01-09 07:40 UTC
### Environment

  * Android device:  Nexus 4
  * Android OS version: 6.0.1
  * Google Play Services version: 11.4.2
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.1.0
  
#### Caused by java.lang.IndexOutOfBoundsException:

  ```
 ava.lang.Character.codePointAt (Character.java:1768)
com.firebase.ui.auth.ui.phone.CountryInfo.localeToEmoji (CountryInfo.java:46)
com.firebase.ui.auth.ui.phone.CountryListSpinner.setSpinnerText (CountryListSpinner.java:75)
com.firebase.ui.auth.ui.phone.CountryListSpinner.setSelectedForCountry (CountryListSpinner.java:83)
com.firebase.ui.auth.ui.phone.VerifyPhoneNumberFragment.setCountryCode (VerifyPhoneNumberFragment.java:273)
com.firebase.ui.auth.ui.phone.VerifyPhoneNumberFragment.onActivityCreated (VerifyPhoneNumberFragment.java:150)
android.support.v4.app.Fragment.performActivityCreated (Fragment.java:2363)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1442)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1740)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1809)
android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:799)
android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2580)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2367)
android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2322)
android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2229)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3221)
android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:3171)
android.support.v4.app.FragmentController.dispatchActivityCreated (FragmentController.java:192)
android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:560)
android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:177)
com.firebase.ui.auth.ui.phone.PhoneVerificationActivity.onStart (PhoneVerificationActivity.java:110)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1237)
android.app.Activity.performStart (Activity.java:6297)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2382)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2479)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1347)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5420)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
  ```

**Comment by samtstern** [comment] 2018-01-09 16:00
This is a duplicate of #779 so I am closing it.  In version `3.1.1` we added some more helpful logs to this issue so if you run into it on `3.1.1` or later please post your logs so we can analyze!

**Closed by samtstern** 2018-01-09 16:00 UTC
