### ISSUE TITLE
com.google.android.gms:play-services-safetynet:17.0.0 alert when publish app

### ISSUE THREAD

**Issue by GGJdevelope** [firebase/FirebaseUI-Android#2047] opened 2022-07-15 08:50 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: any
  * Android OS version:any
  * Google Play Services version: com.google.gms:google-services:4.3.13
  * 
  * Firebase/Play Services SDK version: 
  * com.google.firebase:firebase-bom:30.1.0
  * com.google.android.gms:play-services-auth:20.2.0
  * com.google.firebase:firebase-core:21.0.0
  * 
  * FirebaseUI version:
  *  com.firebaseui:firebase-ui-auth:8.0.1
  
#### Steps to reproduce:

  1. use firebaseui auth phone

  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  * on playconsole:
  * The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline
  
I think
com.google.android.gms:play-services-safetynet:18.0.1 needs to be implemented not 17.0.0

Thanks!

**Comment by thatfiredev** [comment] 2022-07-15 11:43
Hi @GGJdevelope 
This is not a bug in FirebaseUI itself, but on the Firebase Android SDK. There's already an open issue for this: https://github.com/firebase/firebase-android-sdk/issues/3890 I would suggest you follow that issue instead.
I'm closing this one

**Closed by thatfiredev** 2022-07-15 11:43 UTC
