### ISSUE TITLE
Data privacy Issue

### ISSUE THREAD

**Issue by simon944** [firebase/FirebaseUI-Android#1624] opened 2019-04-26 14:59 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
### Step 3: Describe the problem:

Issue: at the moment a user, who is newly registering, does not need to set a checkmark by himself, that he accepts the data privacy policy and the general terms and conditions. -> this leads to an problem: according to the new DSGVO (data privacy laws), a user needs to actively commit, that he approved with the data privacy policy. 

#### Steps to reproduce:

  1. Register new Account

#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * Before clicking on register -> mandatory checkmark, that user approves with the data privacy policy and the general terms & conditions -> mandatory before being able to register account.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by simon944** [comment] 2019-04-26 14:59
thanks :)

**Comment by samtstern** [comment] 2019-04-26 15:17
Thanks for reporting @simon944.  I believe this is a duplicate of #1338

**Closed by samtstern** 2019-04-26 15:17 UTC
