### ISSUE TITLE
NPE on Facebook network error

### ISSUE THREAD

**Issue by LissF** [firebase/FirebaseUI-Android#1049] opened 2017-12-13 11:36 UTC
Hello!

  * Android device: Nexus 5X
  * Android OS version: 8.0.0
  * Google Play Services version: 11.9.51 (440-177350961)
  * Firebase/Play Services SDK version: 11.6.2
  * FirebaseUI version: 3.1.0

Everything was working fine for me, but today I've tried to login with Facebook (I have Facebook Lite installed) but got a crash. I think it was because of a FB network error. Other services were fine. Here are the logs: 

```
E/FacebookProvider: Received Facebook error: java.net.ConnectException: Failed to connect to graph.facebook.com/31.13.81.9:443
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 19338
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.setResult(int, android.content.Intent)' on a null object reference
        at com.firebase.ui.auth.ui.FragmentBase.finish(FragmentBase.java:53)
        at com.firebase.ui.auth.util.signincontainer.IdpSignInContainer.onFailure(IdpSignInContainer.java:159)
        at com.firebase.ui.auth.provider.FacebookProvider.onFailure(FacebookProvider.java:194)
        at com.firebase.ui.auth.provider.FacebookProvider.access$000(FacebookProvider.java:49)
        at com.firebase.ui.auth.provider.FacebookProvider$1.onCompleted(FacebookProvider.java:131)
        at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:301)
        at com.facebook.GraphRequest$5.run(GraphRequest.java:1380)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by SUPERCILEX** [comment] 2017-12-14 23:23
@samtstern I believe this is just another state issue which will be fixed by the refactor. So dup of https://github.com/firebase/FirebaseUI-Android/issues/856.

**Comment by samtstern** [comment] 2017-12-14 23:36
Ok closing as duplicate of #856.

**Closed by samtstern** 2017-12-14 23:36 UTC
