### ISSUE TITLE
Google Provider overrides Facebook account

### ISSUE THREAD

**Issue by macsinte** [firebase/FirebaseUI-Android#896] opened 2017-09-08 02:52 UTC
Hello, I am having a problem where if I use the error indicating 'auth/account-exists-with-different-credential' as described in the Firebase documents, Facebook correctly identifies the already existing account and throws an error, but Google just overrides the existing Facebook account in case the same email is being used.

**Comment by samtstern** [comment] 2017-09-08 20:36
@macsinte what you are describing sounds like the intended behavior.  Google accounts can be merged onto existing accounts because we (Firebase/Google) can safely verify the user's email address.  In this way the Google provider is somewhat different than the others.

I understand this can be confusing, but it's not a bug.  And because this functionality is determined by the Firebase authentication backend and not this library (FirebaseUI) I am going to close this issue,=.

**Closed by samtstern** 2017-09-08 20:36 UTC
