### ISSUE TITLE
Update firebase auth 

### ISSUE THREAD

**Issue by PeterHdd** [firebase/FirebaseUI-Android#1633] opened 2019-05-12 15:01 UTC
**Problem:**

If someone is using `firebase-ui-auth` with the latest version of the following firebase libraries:

```
firebase-firestore
firebase-database
firebase-storage
firebase-function
```

The following error will occur:

>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: meter.meter, PID: 13588
    java.lang.NoSuchMethodError: No virtual method setTokenProvider(Lcom/google/firebase/internal/InternalTokenProvider;)V in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/meter.meter-Qosf8nECYGfI4HI93CwJrw==/split_lib_dependencies_apk.apk!classes2.dex)
        at com.google.firebase.auth.zzp.create(Unknown Source:4)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-common@@17.0.0:66)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-common@@17.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-common@@17.0.0:155)
        at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@17.0.0:642)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:358)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:321)

**Solution:**

Update the following in `Config.kt` to prevent the above issue:

    const val auth = "com.google.firebase:firebase-auth:16.0.5"

into this:

    const val auth = "com.google.firebase:firebase-auth:17.0.0"

For reference:

[Release notes](https://firebase.google.com/support/release-notes/android#update_-_may_07_2019)

Also this was asked on stackoverflow:

[java.lang.NoSuchMethodError: No virtual method setTokenProvider](https://stackoverflow.com/questions/56099945/java-lang-nosuchmethoderror-no-virtual-method-settokenprovider)

**Comment by samtstern** [comment] 2019-05-14 05:46
Thanks for reporting this!  We'll definitely include this in the next
release.

*From: *Peter <notifications@github.com>
*Date: *Sun, May 12, 2019, 8:01 AM
*To: *firebase/FirebaseUI-Android
*Cc: *Subscribed

*Problem:*

**Comment by MonikaJethani** [comment] 2019-05-14 14:47
@samtstern Can I work on this?

**Comment by PeterHdd** [comment] 2019-05-14 16:33
@MonikaJethani it's probably not that hard. 

First you need to update the version, then you need to check if it compatible with other versions and if it will fail on build and then you need to check if the Firebase Auth methods used in this library got deprecated when upgrading to version 17.0.0

**Comment by samtstern** [comment] 2019-05-14 20:51
@MonikaJethani I appreciate the enthusiasm but I think most of the work here has to do with the release process, we shouldn't need any code changes besides a change to `Constants.kt`

**Comment by samtstern** [comment] 2019-05-21 20:01
Closing as duplicate of #1606, fixing this now.

**Closed by samtstern** 2019-05-21 20:01 UTC

**Comment by Pravesh701** [comment] 2019-05-29 16:19
hey same issue with me but not solve by using  const val auth = "com.google.firebase:firebase-auth:17.0.0"
help me please...

**Comment by PeterHdd** [comment] 2019-05-29 16:23
It's better if you ask your issue on stackoverflow. Add the list of dependencies (build.gradle) in your question and the error that you are getting. 

Also add a link to the Stackoverflow question so I can check it
