### ISSUE TITLE
Twitter login error (Activity must not be null)

### ISSUE THREAD

**Issue by caiodev** [firebase/FirebaseUI-Android#992] opened 2017-10-26 16:45 UTC
### Describe your environment

  * Android device: LG L PRIME D337 / RAM: 1GB
  * Android OS version: 5.0 Lollipop
  * Google Play Services version: 3.1.0
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.1.0
  
### Step 3: Describe the problem:
When i try to login using Twitter option the app crashes

#### Steps to reproduce:

  1. Click the Twitter login button
  2. Put your credentials on the screen that shows up
  3. Click the login button
  4. When the user is redirected, the app crashes
  
#### Observed Results:
10-26 13:51:19.208 5148-5148/br.com.teamacai.notedoctor E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: br.com.teamacai.notedoctor, PID: 5148
                                                                          java.lang.NullPointerException: Activity must not be null
                                                                              at com.google.android.gms.common.internal.zzbp.zzb(Unknown Source)
                                                                              at com.google.android.gms.common.api.internal.zzcf.<init>(Unknown Source)
                                                                              at com.google.android.gms.common.api.GoogleApiClient$Builder.enableAutoManage(Unknown Source)
                                                                              at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:219)
                                                                              at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:88)
                                                                              at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:76)
                                                                              at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete(CredentialSignInHandler.java:67)
                                                                              at com.google.android.gms.tasks.zzf.run(Unknown Source)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
10-26 13:51:19.304 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.305 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.307 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.308 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.312 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.315 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.319 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.321 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.346 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.355 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.360 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.362 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.365 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.366 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
10-26 13:51:19.370 1564-6239/? E/Dropbox: null InputStream
                                          java.io.IOException: null InputStream
                                              at afmu.a(:com.google.android.gms@11509234:16)
                                              at afmu.a(:com.google.android.gms@11509234:42)
                                              at aflw.a(:com.google.android.gms@11509234:9)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:21)
                                              at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@11509234:103)
                                              at sto.run(:com.google.android.gms@11509234:1)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  That the app doesn't crash, the login is working, but it crashes.
  
#### Relevant Code:

//Gradle dependencies (app level):,

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "br.com.teamacai.notedoctor"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        resConfigs "auto"
        resValue "string", "google_maps_key", "google_maps_key"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

def BUTTER_KNIFE_VERSION = "8.8.1"

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile "com.jakewharton:butterknife:$BUTTER_KNIFE_VERSION"
    annotationProcessor "com.jakewharton:butterknife-compiler:$BUTTER_KNIFE_VERSION"
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.android.support:palette-v7:26.1.0'
    compile 'com.google.android.gms:play-services-location:11.4.2'
    compile 'com.google.android.gms:play-services-maps:11.4.2'
    compile 'com.google.android.gms:play-services-auth:11.4.2'
    compile 'com.google.firebase:firebase-core:11.4.2'
    compile 'com.google.firebase:firebase-database:11.4.2'
    compile 'com.google.firebase:firebase-storage:11.4.2'
    compile 'com.google.firebase:firebase-messaging:11.4.2'
    compile 'com.google.firebase:firebase-auth:11.4.2'
    compile 'com.google.firebase:firebase-config:11.4.2'
    compile 'com.firebaseui:firebase-ui:3.1.0'
    compile 'com.firebaseui:firebase-ui-database:3.1.0'
    compile 'com.firebaseui:firebase-ui-storage:3.1.0'
    compile 'com.firebaseui:firebase-ui-auth:3.1.0'
    compile 'com.facebook.android:facebook-android-sdk:4.27.0'
    compile 'com.facebook.android:facebook-login:[4,5)'
    compile("com.twitter.sdk.android:twitter-core:3.0.0@aar") { transitive = true }
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.jakewharton.butterknife'

//Gradle file (project level level):

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
        classpath 'com.google.gms:google-services:3.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url 'https://maven.fabric.io/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

//Login Activity:
public class LoginOptionsActivity extends AppCompatActivity {

    private static final int RC_SIGN_IN = 123;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_login_options);

        FirebaseAuth auth = FirebaseAuth.getInstance();
        if (auth.getCurrentUser() != null) {
            // already signed in
            startActivity(new Intent(getApplicationContext(), MainActivity.class));

        } else {
            // not signed in
            startActivityForResult(
                    // Get an instance of AuthUI based on the default app
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(
                                    Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                                            new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                                            new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
                                            new AuthUI.IdpConfig.Builder(AuthUI.TWITTER_PROVIDER).build())
                            ).build(), RC_SIGN_IN);
        }
    }
}

Thanks in advance

**Comment by SUPERCILEX** [comment] 2017-10-26 17:17
Yeah, sadly we've tried adding various hacks over the past few months, but none of them have worked very well. Now we're taking the fundamental approach and rearchitecting FUI which is going to take time unfortunately. No quick fix coming that I know of. 😊

**Comment by caiodev** [comment] 2017-10-26 17:24
I see @SUPERCILEX, it's hard because FUI is huge. There's a lot of code involved. But I really look forward to see this bug fixed. You guys are doing a terrific job keeping FUI alive, it really saves us much time during development. We, developers appreciate that. Thanks for it 👍

**Comment by samtstern** [comment] 2017-10-26 21:19
@caiodev thanks for the kind words
@SUPERCILEX thanks for jumping in!

Closing as duplicate of #856

**Closed by samtstern** 2017-10-26 21:19 UTC
