### ISSUE TITLE
Error inflating class com.firebase.ui.auth.util.ui.BaselineTextInputLayout

### ISSUE THREAD

**Issue by Praveena0989** [firebase/FirebaseUI-Android#1595] opened 2019-03-07 17:45 UTC
### Step 1: Are you in the right place?
yes

### Step 2: Describe your environment

  * Android device: Samsung J6
  * Android OS version: 8(api 26)
  * Google Play Services version: 
  * Firebase/Play Services SDK version: 16.0.5
  * FirebaseUI version: 4.3.1
  
### Step 3: Describe the problem:
I am setting custom UI theme to firebase auth

    <style name="LoginTheme" parent="Theme.AppCompat.Light.NoActionBar"> 
      <item name="colorPrimaryDark">@color/statusBar</item> 
      <item name="android:windowLightStatusBar">true</item> 
      <item name="colorPrimary">#fff</item> 
      <item name="colorAccent">@color/primary</item> 
    </style>

But it is failing in one device(could be more also) and I don't have access to that device as I got crash report in crashalytics.

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfocom.firebase.ui.auth.ui.phone.PhoneActivity}: android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class com.firebase.ui.auth.util.ui.BaselineTextInputLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by samtstern** [comment] 2019-03-08 17:28
Hmmm this does seem like a bug but without a way to reproduce it on a device or an emulator I don't know how I could go about fixing it.   These inflation errors are always tricky to hunt down.

**Comment by Praveena0989** [comment] 2019-03-18 04:48
@samtstern  Issue is happening also on Nexus 5x(Android version 6.0.1)

**Comment by Praveena0989** [comment] 2019-03-26 19:40
@samtstern  any update on this issue

**Comment by samtstern** [comment] 2019-03-26 20:09
@Praveena0989 no not yet, I haven't been able to get this to happen for myself...

**Comment by samtstern** [comment] 2019-11-21 22:28
Since we plan to kill the problematic class (https://github.com/firebase/FirebaseUI-Android/issues/1464) as soon as the Google Material library hits `1.1.0` I am going to close this bug as a duplicate of #1464

**Closed by samtstern** 2019-11-21 22:28 UTC
Labels: auth, help-wanted, type: bug
