### ISSUE TITLE
Odd placement of Login buttons in AuthUI

### ISSUE THREAD

**Issue by the-dagger** [firebase/FirebaseUI-Android#521] opened 2017-01-13 14:40 UTC
### Step 2: Describe your environment

  * Android device: OnePlus3
  * Android OS version: 7.0
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.0
  
### Step 3: Describe the problem:
Odd placement of login buttons in Authentication Screen
#### Steps to reproduce:
Try to login.
#### Observed Results:

 
![screenshot_20170113-200527](https://cloud.githubusercontent.com/assets/6565270/21933659/3aa09434-d9cc-11e6-805e-395156293db3.png)

  
#### Expected Results:

![screenshot_20170113-200842](https://cloud.githubusercontent.com/assets/6565270/21933660/3cef1a80-d9cc-11e6-9aa6-cce556626fcc.png)

**Comment by samtstern** [comment] 2017-01-13 15:43
This was caused by me in #515, and it can be worked around by setting a logo with `setLogo()`.  I realize now we neglected to test the layout without setLogo() which causes the buttons to float to the top in the absence of one.

I will probably release a `1.1.1` version to fix this issue.

**Comment by samtstern** [comment] 2017-01-13 22:42
This has been fixed by `1.1.1`

**Closed by samtstern** 2017-01-13 22:42 UTC
Labels: bug, feature:auth
