### ISSUE TITLE
NullPointerException BaseHelper.finishActivity(BaseHelper.java:51)

### ISSUE THREAD

**Issue by MobilefactoryAT** [firebase/FirebaseUI-Android#666] opened 2017-04-15 07:14 UTC
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=0, data=Intent { (has extras) }} to activity {com.nastylion.gifi/com.firebase.ui.auth.KickoffActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3601)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3644)
       at android.app.ActivityThread.access$1300(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5342)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.firebase.ui.auth.ui.BaseHelper.finishActivity(BaseHelper.java:51)
       at com.firebase.ui.auth.ui.FragmentHelper.finish(FragmentHelper.java:28)
       at com.firebase.ui.auth.ui.FragmentBase.finish(FragmentBase.java:26)
       at com.firebase.ui.auth.util.signincontainer.IdpSignInContainer.onFailure(IdpSignInContainer.java:148)
       at com.firebase.ui.auth.provider.FacebookProvider.onFailure(FacebookProvider.java:192)
       at com.firebase.ui.auth.provider.FacebookProvider.onCancel(FacebookProvider.java:166)
       at com.facebook.login.LoginManager.finishLogin(LoginManager.java:573)
       at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:216)
       at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:159)
       at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
       at com.firebase.ui.auth.provider.FacebookProvider.onActivityResult(FacebookProvider.java:123)
       at com.firebase.ui.auth.util.signincontainer.IdpSignInContainer.onActivityResult(IdpSignInContainer.java:157)
       at com.firebase.ui.auth.util.signincontainer.SignInDelegate.onActivityResult(SignInDelegate.java:179)
       at com.firebase.ui.auth.KickoffActivity.onActivityResult(KickoffActivity.java:82)
       at android.app.Activity.dispatchActivityResult(Activity.java:5545)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3597)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3644)
       at android.app.ActivityThread.access$1300(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5342)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by SUPERCILEX** [comment] 2017-04-15 15:50
@MobilefactoryAT Yup, this was fixed in #618 and will be available in the `v2.0` release.

**Comment by samtstern** [comment] 2017-04-17 15:18
@MobilefactoryAT going to fix this since it's a duplicate of #618, thanks for taking the time to report it.

**Closed by samtstern** 2017-04-17 15:18 UTC
