### ISSUE TITLE
Unable to install locally

### ISSUE THREAD

**Issue by jeffy2007** [firebase/FirebaseUI-Android#1256] opened 2018-04-16 03:00 UTC
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Android device: NA
  * Android OS version: NA
  * Google Play Services version: 48
  * Firebase/Play Services SDK version: 12.0.1
  * FirebaseUI version: 3.3.0
  
### Step 3: Describe the problem:

Unable to install locally by using **gradlew :library:prepareArtifacts :library:publishAllToMavenLocal**

#### Steps to reproduce:

  1. Clone this repository
  2. Open it with android studio
  3. Run gradlew :library:prepareArtifacts :library:publishAllToMavenLocal in terminal
  
#### Observed Results:

```
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':firestore:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':common:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/jeffy/Desktop/Git/FirebaseUI-Android/common/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':database:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/jeffy/Desktop/Git/FirebaseUI-Android/database/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
87 actionable tasks: 34 executed, 46 from cache, 7 up-to-date
```
  
#### Expected Results:

Build successfully
  
#### Relevant Code:
NA

**Comment by samtstern** [comment] 2018-04-16 15:52
@jeffy2007 thanks for filing this issue, and cool that you're trying local development!

Could you show the contents of this file?
` '/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/build/tmp/javadoc/javadoc.options'`

**Comment by jeffy2007** [comment] 2018-04-17 00:28
@samtstern Thanks for the reply.

Herein the content:
-Xdoclint:none '-quiet'
-classpath '/Users/jeffy/Library/Android/sdk/platforms/android-27/android.jar'
-d '/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/build/docs/javadoc'
-doctitle 'firestore API'
-quiet 
-windowtitle 'firestore API'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/ClassSnapshotParser.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/FirestoreRecyclerAdapter.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/FirestoreArray.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/ChangeEventListener.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/FirestoreRecyclerOptions.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/SnapshotParser.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/ObservableSnapshotArray.java'
'/Users/jeffy/Desktop/Git/FirebaseUI-Android/firestore/src/main/java/com/firebase/ui/firestore/CachingSnapshotParser.java'

**Comment by jeffy2007** [comment] 2018-04-28 03:29
@samtstern sorry for the late reply. I am able to build with -x javadoc flag successfully. But by the command without the flag i am still getting failure.

Thank you for the help :)

**Comment by samtstern** [comment] 2018-05-14 15:07
@jeffy2007 going to close this issue for now since we don't actually use the Javadoc anyway so I don't see `-x javadoc` as being a bad experience and I don't have a computer to reproduce this on.

**Closed by samtstern** 2018-05-14 15:07 UTC
Labels: internal
