### ISSUE TITLE
Error after every login with Google and email

### ISSUE THREAD

**Issue by Lamba92** [firebase/FirebaseUI-Android#1273] opened 2018-04-27 10:27 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Emuator API 27 w/ Play Services
  * Android OS version: 8.1
  * Google Play Services version: 12.5.29 (040700-192802242)
  * Firebase/Play Services SDK version: 15.0.0
  * FirebaseUI version: 3.3.1
  * Facebook SDK version: 4.20.0
  
### Step 3: Describe the problem:
There is this stack trace every time I login with Google or email:

#### Steps to reproduce:

  1. Log out
  2. Login with google or email
  
#### Observed Results:

```
    Process: it.unito.lamba.projector, PID: 5710
    java.lang.NoSuchMethodError: No virtual method unregisterCallback(Lcom/facebook/CallbackManager;)V in class Lcom/facebook/login/LoginManager; or its super classes (declaration of 'com.facebook.login.LoginManager' appears in /data/app/it.unito.lamba.projector-6GSNo362zawjstAR6JehiA==/split_lib_dependencies_apk.apk)
        at com.firebase.ui.auth.data.remote.FacebookSignInHandler.onCleared(FacebookSignInHandler.java:106)
        at android.arch.lifecycle.ViewModelStore.clear(ViewModelStore.java:57)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:387)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at com.firebase.ui.auth.ui.HelperActivityBase.onDestroy(HelperActivityBase.java:53)
        at android.app.Activity.performDestroy(Activity.java:7218)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
  
#### Expected Results:

 No errors i guess
  
#### Relevant Code:

  ```
      @Override
    protected void onCleared() {
        super.onCleared();
        LoginManager.getInstance().unregisterCallback(mCallbackManager);
    }
  ```

**Comment by Lamba92** [comment] 2018-04-27 16:41
Meanwhile I edited a lot of stff in the project and the error seems gone. The main changes I think i did to mitigate the error whre add the string **fb** in the resource `facebook_login_protocol_scheme` and switch from `implementation 'com.facebook.android:facebook-android-sdk:4.20.0'` to `implementation 'com.facebook.android:facebook-login:[4,5)'`. I'm attaching the dependency tree as is now, unfortunately I do not have a snapshot of the project of when I had the error.

[dep.txt](https://github.com/firebase/FirebaseUI-Android/files/1955904/dep.txt)

**Comment by samtstern** [comment] 2018-04-27 16:47
@Lamba92 thanks for the update.  I am going to close this since we can't reproduce right now but if it happens again just let me know and I'll re-open it!

**Closed by samtstern** 2018-04-27 16:47 UTC
