### ISSUE TITLE
Null Pointer Exception crash using PhoneAuth in ver 2.4.0

### ISSUE THREAD

**Issue by yajur96** [firebase/FirebaseUI-Android#988] opened 2017-10-18 13:31 UTC
I have an app released in the Google Play Store. Recently, I observed a crash due to the following null pointer exception in FirebaseUI phone auth.

Device - Xiaomi HM 2LTE-IN (HM2014818) (Android 5.1)
Used the following dependancy : compile 'com.firebaseui:firebase-ui-auth:2.4.0'
Here is the log:
java.lang.NullPointerException: 
  at android.support.v4.app.DialogFragment.dismissInternal (DialogFragment.java:200)
  at android.support.v4.app.DialogFragment.dismissAllowingStateLoss (DialogFragment.java:181)
  at com.firebase.ui.auth.ui.phone.PhoneVerificationActivity.dismissLoadingDialog (PhoneVerificationActivity.java:398)
  at com.firebase.ui.auth.ui.phone.PhoneVerificationActivity.showLoadingDialog (PhoneVerificationActivity.java:387)
  at com.firebase.ui.auth.ui.phone.PhoneVerificationActivity.verifyPhoneNumber (PhoneVerificationActivity.java:157)
  at com.firebase.ui.auth.ui.phone.VerifyPhoneNumberFragment.onNext (VerifyPhoneNumberFragment.java:200)
  at com.firebase.ui.auth.ui.phone.VerifyPhoneNumberFragment.access$000 (VerifyPhoneNumberFragment.java:55)
  at com.firebase.ui.auth.ui.phone.VerifyPhoneNumberFragment$1.onDonePressed (VerifyPhoneNumberFragment.java:102)
  at com.firebase.ui.auth.ui.ImeHelper$1.onEditorAction (ImeHelper.java:29)
  at android.widget.TextView.onEditorAction (TextView.java:4490)
  at com.android.internal.widget.EditableInputConnection.performEditorAction (EditableInputConnection.java:139)
  at com.android.internal.view.IInputConnectionWrapper.executeMessage (IInputConnectionWrapper.java:304)
  at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage (IInputConnectionWrapper.java:78)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5290)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:911)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:706)

**Comment by samtstern** [comment] 2017-10-18 15:23
Duplicate of #985

**Closed by samtstern** 2017-10-18 15:23 UTC
Labels: bug, feature:auth
