### ISSUE TITLE
Landscape Layout in Authentication Method Picker

### ISSUE THREAD

**Issue by HusseinElFeky** [firebase/FirebaseUI-Android#375] opened 2016-10-22 21:33 UTC
I have a small issue, but it can be very easily fixed. In the Authentication Method Picker activity, I put a logo and 3 providers (3 buttons). In portrait mode, everything looks neat and fine, but in landscape mode, the image is very small because there is no place for it above the 3 buttons. So I would suggest, in landscape mode, that if the developer decides to put a logo, the logo should be shown at the left, and the buttons should be shown at the right. This will be a much better approach.

**Comment by SUPERCILEX** [comment] 2016-10-23 22:50
We should probably use constraint layout to reduce nesting. Also, from what I understand, `View.GONE` rebuilds all the constraints so it would make supporting landscape layouts easier.

**Comment by Akshit94** [comment] 2016-12-16 11:51
I made a workaround for this issue. I don't know whether it's correct or not but it's working just fine. What I did was made a copy of the  "**auth_method_picker_layout.xml**" file in the library in my own "**layout-land**" folder and tweaked the layout a little bit to suit my needs. This layout overrides the original layout in the library. @HusseinElFeky you can try this approach if you want to.

**Comment by HusseinElFeky** [comment] 2016-12-16 11:59
@Akshit94 @SUPERCILEX Yes, that's definitely correct. That's the way it should be implemented. It will be much better if it is added in the next version though.

**Comment by samtstern** [comment] 2017-01-31 23:49
This issue is a duplicate of #522 and a fix for the auth method picker has been implemented in #562, look out for version `1.2.0`!

**Closed by samtstern** 2017-01-31 23:49 UTC
