### ISSUE TITLE
AuthUI flow starts multiple times when rotated and then crashes when selecting an account for each instance

### ISSUE THREAD

**Issue by oviroa** [firebase/FirebaseUI-Android#549] opened 2017-01-26 11:26 UTC
### Step 2: Describe your environment

  * Android device: Pixel XL
  * Android OS version: 7.1.1
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1
  
### Step 3: Describe the problem:
Account selector UI that overlays on top of the root UI gets created multiple times, once with every orientation change rotation. Then, I have to tap on the desired account once for each instance, as they disappear one by one, and after the last one, app crashes:

01-26 03:14:10.381 20689-20689/oviroa.bestshot.android E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.setResult(int, android.content.Intent)' on a null object reference
                                                                                at com.firebase.ui.auth.ui.BaseHelper.finishActivity(BaseHelper.java:51)
                                                                                at com.firebase.ui.auth.ui.FragmentHelper.finish(FragmentHelper.java:27)
                                                                                at com.firebase.ui.auth.ui.FragmentBase.finish(FragmentBase.java:26)
                                                                                at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.finish(SaveSmartLock.java:178)
                                                                                at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:198)
                                                                                at com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish(BaseHelper.java:124)
                                                                                at com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish(BaseHelper.java:112)
                                                                                at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete(CredentialSignInHandler.java:68)
                                                                                at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-26 03:14:10.689 20689-20689/oviroa.bestshot.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: oviroa.bestshot.android, PID: 20689
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.setResult(int, android.content.Intent)' on a null object reference
                                                                             at com.firebase.ui.auth.ui.BaseHelper.finishActivity(BaseHelper.java:51)
                                                                             at com.firebase.ui.auth.ui.FragmentHelper.finish(FragmentHelper.java:27)
                                                                             at com.firebase.ui.auth.ui.FragmentBase.finish(FragmentBase.java:26)
                                                                             at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.finish(SaveSmartLock.java:178)
                                                                             at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:198)
                                                                             at com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish(BaseHelper.java:124)
                                                                             at com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish(BaseHelper.java:112)
                                                                             at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete(CredentialSignInHandler.java:68)
                                                                             at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

#### Steps to reproduce:

  1. Click on Sign In button, list of Google accounts appears in overlay
  2. Rotate device multiple times... It is visible how a new overlay is create with each orientation change
  3. Tap on desired account, once for each overlay, until all disappear and root view is now clearly visible, then app crashes (see log above)
  
This is the event handler for the button that starts the login process:

```java
    /**
     * Sign in
     */
    @OnClick(R.id.sign_in)
    void signIn() {
        Intent intent = AuthUI.getInstance()
                .createSignInIntentBuilder()
                .setProviders(Collections.singletonList(new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build()))
                .setIsSmartLockEnabled(false)
                .setTheme(R.style.AppTheme_NoActionBar)
                .setLogo(R.drawable.ic_logo)
                .build();
        startActivityForResult(
                intent,
                RC_SIGN_IN);
    }
```

**Comment by SUPERCILEX** [comment] 2017-01-27 01:24
@oviroa thanks for this report, that's a very interesting race condition. I'll see if I can fix in `v1.2.0`.

PS: as a temporary workaround, just add another provider (eg minimum of two providers) or enable smart lock (that just delays the rotation bug though).

**Comment by oviroa** [comment] 2017-01-27 01:36
Thanks for the response. I don't have a use-case for multiple providers but I ended up with something similar to what you are proposing, by disallowing an orientation change while the overlay is enabled by adding: setRequestedOrientation (ActivityInfo.SCREEN_ORIENTATION_LOCKED) before startActivityForResult.

**Comment by SUPERCILEX** [comment] 2017-01-27 01:43
@oviroa This will be fixed in `v1.2.0`.

**Comment by oviroa** [comment] 2017-01-27 01:44
What is the ETA for release?

**Comment by SUPERCILEX** [comment] 2017-01-27 01:46
@oviroa I don't actually work for Firebase, so @samtstern would be the best person to ask for this. (Though I'd guess a few weeks at most).

**Comment by samtstern** [comment] 2017-01-27 16:59
No ETA at the moment, but historically releases are separated by a few weeks or a month.  `1.1.1` is fairly recent.

**Closed** 2017-02-21 19:57 UTC
Labels: bug, feature:auth, fix-implemented

**Comment by peterhav** [comment] 2017-03-02 13:52
Using version 1.2.0, I still receive crash reports showing the NPE:

```
Exception java.lang.NullPointerException:
com.firebase.ui.auth.ui.BaseHelper.finishActivity (BaseHelper.java:51)
com.firebase.ui.auth.ui.FragmentHelper.finish (FragmentHelper.java:28)
com.firebase.ui.auth.ui.FragmentBase.finish (FragmentBase.java:26)
com.firebase.ui.auth.util.signincontainer.SaveSmartLock.finish (SaveSmartLock.java:178)
com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish (SaveSmartLock.java:198)
com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish (BaseHelper.java:124)
com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish (BaseHelper.java:112)
com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete (CredentialSignInHandler.java:68)
com.google.android.gms.tasks.zzc$1.run (zzc.java)
android.os.Handler.handleCallback (Handler.java:733)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:157)
android.app.ActivityThread.main (ActivityThread.java:5335)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1265)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1081)
dalvik.system.NativeStart.main (NativeStart.java)
```
Exact environment:
- Android device: Samsung SM-N9005 
- Android OS version: 4.4.2
- Google Play Services version: -
- Firebase/Play Services SDK version: 10.2.0
- FirebaseUI version: 1.2.0

**Comment by SUPERCILEX** [comment] 2017-03-03 00:27
@peterhav I can't reproduce this, but I know it's happened to me too a few times before. While the stacktrace is the same, I think this is a completely different issue than #549. Basically, our fragments stay alive beyond the activity lifecycle so that we can keep logging the user in even if they rotate the screen. This gets a little messy though because we could be trying to finish the activity while it's in no-man's land between an `onDestroy` and an `onCreate`. My guess is that since the phone you mentioned is older and slower, it takes much longer for the activity to recreate and attach itself to our fragments thus increasing the likelihood of a crash. Anyway, hopefully #x will fix this kind of issue once and for all.
