### ISSUE TITLE
App Crashes on some devices at the authentication section

### ISSUE THREAD

**Issue by asishraut1** [firebase/FirebaseUI-Android#1564] opened 2019-01-03 09:05 UTC
On some devices(mainly devices below kitkat) crashes when a user tries to login. this issue started when i upgraded my firebase auth sdk to 16.1.0 and the error is 

```
FATAL EXCEPTION: main 
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/com.app-1.apk 
at android.app.ActivityThread.installProvider(ActivityThread.java:5122) 
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665) 
at android.app.ActivityThread.access$1400(ActivityThread.java:159) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:176) 
at android.app.ActivityThread.main(ActivityThread.java:5419) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/com.app-1.apk 
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:501) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:461) 
at android.app.ActivityThread.installProvider(ActivityThread.java:5107) 
... 12 more 
```

please help me solve this. I am using just Phone authentication provider 

```java
startActivityForResult( 
AuthUI.getInstance() 
.createSignInIntentBuilder() 
.setAvailableProviders(Arrays.asList( 
new AuthUI.IdpConfig.PhoneBuilder().build())) 
.setTheme(R.style.LoginTheme) 
.build(), 
RC_SIGN_IN); 
}
```

**Comment by samtstern** [comment] 2019-01-03 16:53
@asishraut1 there's no indication from your stack trace that this bug is caused by FirebaseUI, so I am going to close this issue.

Please look at this StackOverflow post, which may have a solution to your problem:
https://stackoverflow.com/questions/39825543/didnt-find-class-com-google-firebase-provider-firebaseinitprovider

**Closed by samtstern** 2019-01-03 16:53 UTC
