### ISSUE TITLE
println needs a message - SaveSmartLock

### ISSUE THREAD

**Issue by plugie** [firebase/FirebaseUI-Android#673] opened 2017-04-25 16:18 UTC
Android Device:
Manufacturer: MITO
Model: MITO_A10
Android API: 23
Android OS: 6.0.1
Brand: Google
RAM: 965.54MB
Google Play Service : 10.2.98
Firebase/Play Services SDK version : 10.2.0
FirebaseUI version : 1.2.0

Describe the problem:
Crash when try to login. But login is success. It means auth.getCurrentUser() is not null after crash is happen. 
The problem **doesn't happen** in other two of my mobile phone, i.e.: Samsung Galaxy S5 and honor 6

Steps to reproduce:
1. Login using firebase-ui. There are two methods : Google and Facebook
2. Touch Google sign in button
3. Choose my Google account
4. Then crash with error below : 

> Exception java.lang.NullPointerException: println needs a message
> android.util.Log.println_native (Log.java)
> android.util.Log.w (Log.java:181)
> com.firebase.ui.auth.util.signincontainer.SaveSmartLock.getInstance (SaveSmartLock.java)
> <OR>.onConnected (SaveSmartLock.java)
> <OR>.onConnectionFailed (SaveSmartLock.java)
> <OR>.onResult (SaveSmartLock.java)
> <OR>.onActivityResult (SaveSmartLock.java)
> <OR>.saveCredentialsOrFinish (SaveSmartLock.java)
> <OR>.onResult (SaveSmartLock.java)
> com.firebase.ui.auth.util.signincontainer.SaveSmartLock.getInstance (SaveSmartLock.java)
> <OR>.onConnected (SaveSmartLock.java)
> <OR>.onConnectionFailed (SaveSmartLock.java)
> <OR>.onResult (SaveSmartLock.java)
> <OR>.onActivityResult (SaveSmartLock.java)
> <OR>.saveCredentialsOrFinish (SaveSmartLock.java)
> <OR>.onResult (SaveSmartLock.java)
> com.google.android.gms.internal.zzaaf$zza.zzb (zzaaf.java)
> com.google.android.gms.internal.zzaaf$zza.handleMessage (zzaaf.java)
> android.os.Handler.dispatchMessage (Handler.java:102)
> android.os.Looper.loop (Looper.java:148)
> android.app.ActivityThread.main (ActivityThread.java:5417)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Relevant Code:

> startActivityForResult(
>                             AuthUI.getInstance()
>                                     .createSignInIntentBuilder()
>                                     .setTheme(R.style.AppTheme)
>                                     .setProviders(Arrays.asList(
>                                             new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
>                                             new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build()))
>                                     .build(),
>                             RC_SIGN_IN);

**Comment by SUPERCILEX** [comment] 2017-04-25 17:59
@plugie This is a mistake on our part caused by some Google Play Services changes. It'll be fixed in `v2.0` at the latest, but possibly earlier depending on whether or not @samtstern wants to release a patch version.

**Closed** 2017-06-12 16:55 UTC
Labels: bug, fix-implemented
