### ISSUE TITLE
Google login issue while adding new account using FirebaseUI Auth

### ISSUE THREAD

**Issue by dhawaljaiswal** [firebase/FirebaseUI-Android#1335] opened 2018-06-01 10:57 UTC
### Step 1: Are you in the right place?
I am using google firebase UI Auth For login purpose, I found that when we try to login with the new account then the app shows loading dialog and it run continuously until we stop it by touching on the screen, after that if we try again for login it works smoothly as the account has been saved now, how to fix this issue, I am attaching gif file 

![firebase-google-login-issue](https://user-images.githubusercontent.com/5075117/40837594-9d3f47d8-65b8-11e8-8128-0d36ce2203f0.gif)

### Step 2: Describe your environment
  * Android device: **Motorola Nexus 6** 
  * Android OS version: Android 7.1.1 
  * Google Play Services version: com.google.gms:google-services:3.2.0, 
  * Firebase/Play Services SDK version:  'com.google.android.gms:play-services-auth:15.0.1', 
                                                               'com.google.firebase:firebase-auth:15.1.0'
  * FirebaseUI version:  'com.firebaseui:firebase-ui-auth:3.2.2'
  
### Step 3:Our Code:
`public class SignInActivity extends BaseActivity  {
    public static final String TAG = SignInActivity.class.getSimpleName();

    private static final int RC_SIGN_IN = 100;
    View mRootView;
    FirebaseAuth firebaseAuth;
    FirebaseFirestore db = FirebaseFirestore.getInstance();
    List<AuthUI.IdpConfig> providers;

    ActionBar actionBar;

    private boolean isDeleted;

    public static Intent createIntent(Context context) {
        return new Intent(context, SignInActivity.class);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //setContentView(R.layout.activity_sign_in);

        isDeleted = true;

        firebaseAuth = FirebaseAuth.getInstance();

        providers = Arrays.asList(
                new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).setPermissions(Arrays.asList("email")).build());

        if (firebaseAuth.getCurrentUser() != null){
            startSignedInActivity(null);
            startTransition();
        }else {
            // Create and launch sign-in intent
            startActivityForResult(
            AuthUI.getInstance()
                    .createSignInIntentBuilder()
                    .setTheme(R.style.AppTheme)
                    .setAvailableProviders(providers)
                    .setIsSmartLockEnabled(false)
                    .build(),
            RC_SIGN_IN);
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_SIGN_IN) {
            handleSignInResponse(resultCode, data);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d(TAG, "click onResume");
        firebaseAuth = FirebaseAuth.getInstance();
        if (firebaseAuth.getCurrentUser() != null) {
            startSignedInActivity(null);
        }
    }

    private void handleSignInResponse(int resultCode, Intent data) {
        IdpResponse response = IdpResponse.fromResultIntent(data);

        // Successfully signed in
        if (resultCode == RESULT_OK) {
            Log.d(TAG, "login success");
            startSignedInActivity(response);
        } else {
            // Sign in failed
            if (response == null) {
                // User pressed back button
                showSnackbar(R.string.sign_in_cancelled);
                return;
            }

            if (response.getError().getErrorCode() == ErrorCodes.NO_NETWORK) {
                Toast.makeText(context, "No Network", Toast.LENGTH_SHORT).show();
                return;
            }

            showSnackbar(R.string.unknown_error);
            Log.e(TAG, "Sign-in error: ", response.getError());
        }
    }

    private void startSignedInActivity(IdpResponse response) {
        FirebaseUser currentUser = firebaseAuth.getCurrentUser();
        if (currentUser != null) {
            Toast.makeText(context, "Login success : Welcome, " + currentUser.getDisplayName(), Toast.LENGTH_SHORT).show();
            startActivity(SettingActivity.createIntent(SignInActivity.this, response));
            startTransition();
            finish();
        }
    }

    private void showSnackbar(int errorMessageRes) {
        Toast.makeText(this, getResources().getString(errorMessageRes), Toast.LENGTH_LONG).show();
    }
}`

#### Expected Results:
After login with any new account, the app should redirect to its main screen whereas at present it comes back to the login screen and even its not come automatically we have to stop the loader for that.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by SUPERCILEX** [comment] 2018-06-01 16:00
Looks like a duplicate of https://github.com/googlesamples/google-services/issues/358.

**Comment by samtstern** [comment] 2018-06-06 16:37
@SUPERCILEX is correct, this is a duplicate of that issue.

**Closed by samtstern** 2018-06-06 16:37 UTC
