### ISSUE TITLE
[Internal] Internal error in Firestore (0.6.6-dev).

### ISSUE THREAD

**Issue by superdiazzz** [firebase/FirebaseUI-Android#1542] opened 2018-11-23 12:23 UTC
### Environment
  * Android device: RedMi
  * Android OS version: 4.4.4
  * Firebase/Play Services SDK version: 16.0.5
  * FirebaseUI version: 4.2.1
  
###  Describe the problem:
I switched to using firebase-ui for certain purposes (previously I used firestore only in version 11.8.0). When replacing using Firebase-ui, the firestore used has increased version to 17.1.1 and then crashes

 Steps to reproduce:
  Almost immediately, when connected to firestore realtime events, we get this:

```
java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
        at com.google.firebase.firestore.obfuscated.zzgf.zzb(com.google.firebase:firebase-firestore@@17.1.1:377)
        at com.google.firebase.firestore.obfuscated.zzgk.run(com.google.firebase:firebase-firestore@@17.1.1)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5111)
```
I have researched various ways such as "Clear the data in the application manager on the device.
Then run the app again." but still the same.

### Library
    implementation 'com.firebaseui:firebase-ui-firestore:4.2.1'
    implementation 'com.google.firebase:firebase-auth:16.0.5'
    implementation 'com.google.firebase:firebase-storage:16.0.5'
    implementation 'android.arch.core:runtime:1.1.1'

**Comment by samtstern** [comment] 2018-11-26 18:38
@superdiazzz could you add this dependency:
`implementation 'com.google.firebase:firebase-firestore:17.1.3'`

And then try again?  It may fix your issue and if it does not, we will at least have a better stack trace since releases of `17.1.2` and up are no longer obfuscated (so no more `zzgf.foo` stuff)

**Comment by superdiazzz** [comment] 2018-11-27 14:47
@samtstern 
now an error with the latest version like this
```
Process: com.xsamplegarage.app.custom_in, PID: 9330
    java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@17.1.3:377)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@17.1.3)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5111)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
```

**Comment by samtstern** [comment] 2018-11-27 16:55
@superdiazzz I can't tell without seeing the rest of your stack trace (there should be a "caused by" section) but it's possible it's the same as this issue:
https://github.com/firebase/firebase-android-sdk/issues/115

Could you provide more of the stack trace?

**Comment by superdiazzz** [comment] 2018-11-28 01:21
I think this error can be explored in this part, because the action in the callback is skipped, when I check the console there is a log sequence like the following
```
11-28 08:09:28.262 ? E/RenderScript: Failed loading RS driver: dlopen failed: could not load library "librs_adreno.so" needed by "libRSDriver_adreno.so"; caused by library "librs_adreno.so" not found
    Failed to load runtime libRSDriver_adreno.so, loading default
```
in addition to the source of my problem, I did the following code in firestore:
```
DocumentReference docRef = fdb.collection(Constant.FIRESTORE_DOCUMENT_USER).document(username);
        docRef.get().addOnSuccessListener( documentSnapshot -> {
          // my breakpoint did not reach this  
          Log.d(TAG, "readProfile: " + user.toString());
                 

        }).addOnFailureListener(e -> {
            // also my breakpoint did not reach this
            Log.d(TAG, "readProfile: error " + e);
            
        });
```

**Comment by gsoltis** [comment] 2018-11-28 18:22
Huh, that is more interesting. I was unable to produce this using an emulator at the same Android version. I can confirm that the aforementioned class exists on my classpath. Can you double check to confirm that you only have a single version of firestore on your classpath? Maybe run a clean before building again as well?

**Comment by gsoltis** [comment] 2018-11-28 18:29
Also, see if you can confirm that the class exists in your copy of the library. My copy of the jar is located at `${HOME}/.gradle/caches/transforms-1/files-1.1/firebase-firestore-17.1.3.aar/23021475f9623405571a5c7c5062d58c/jars`, yours may be in a similar location. You can then run `jar -tf classes.jar | grep SQLiteSchema`. You should see a few classes, including `com/google/firebase/firestore/local/SQLiteSchema$$Lambda$2.class`.

**Comment by superdiazzz** [comment] 2018-11-29 07:41
@gsoltis 
I have done clean before building but still give the same results. then when I enter into this path 
`C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-firestore-17.1.3.aar/fd8376ec33d52550b992cd5c78618cf8/jars` then run `jar -tf classes.jar | grep SQLiteSchema` give me results `'jar' is not recognized as an internal or external command,` but when I browse from log error and enter into the jar file. i found a class SQLiteSchema$$Lambda$2, its path as follows `C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-firestore-17.1.3.aar/fd8376ec33d52550b992cd5c78618cf8/jars/classes.jar!/com/google/firebase/firestore/local/SQLiteSchema$$Lambda$2.class:10`

**Comment by gsoltis** [comment] 2018-11-29 18:21
If you run `gradlew.bat app:dependencies` can you confirm that you only have one version of Firestore? It seems like you must have multiple versions of the library being loaded if the class exists in the jar but your application can't find it.

**Comment by superdiazzz** [comment] 2018-12-01 14:51
@gsoltis `gradlew.bat app:dependencies` i run this, then i found only one version firestore. I don't have an idea how to clear or renew library on my path.

**Comment by gsoltis** [comment] 2018-12-04 21:35
Hmm, I would try a clean and rebuild. If that doesn't work, verify your classpath as the app sees it, possibly with a snippet of code as described here: https://www.mkyong.com/java/how-to-print-out-the-current-project-classpath/

**Comment by superdiazzz** [comment] 2018-12-08 08:00
@gsoltis here is my clashpath. After the file is executed. Do you see duplicates? if I search there is only one firestore
```
DEBUG: ExampleUnitTest: /C:/Program%20Files/Android/Android%20Studio1/lib/idea_rt.jar
DEBUG: ExampleUnitTest: /C:/Program%20Files/Android/Android%20Studio1/plugins/junit/lib/junit-rt.jar
DEBUG: ExampleUnitTest: /C:/Program%20Files/Android/Android%20Studio1/plugins/junit/lib/junit5-rt.jar
DEBUG: ExampleUnitTest: /C:/Users/User/AppData/Local/Android/sdk/platforms/android-27/data/res/
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/build/intermediates/classes/test/debug/
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/build/intermediates/classes/debug/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-v4-27.1.1.aar/27880105d75f443448107a7abdec1048/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.1.2/6dcc08f90f678ac33e5ef78c3c752b6f59e63e0c/error_prone_annotations-2.1.2.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/android.arch.lifecycle/common/1.1.0/edf3f7bfb84a7521d0599efa3b0113a0ee90f85/common-1.1.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-core-16.0.5.aar/340c749b92e1c68088e2a9f43429ef0b/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-tasks-16.0.1.aar/e5ac1d5078bac66719de1deebd33edab/jars/classes.jar
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/libs/additionnal.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-common-16.0.4.aar/cbd3305cb23737de58bceda5fdd4e227/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp/okhttp/2.7.5/7a15a7db50f86c4b64aa3367424a60e3a325b8f1/okhttp-2.7.5.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-analytics-16.0.5.aar/9ecf1d0bdf56e49cabcd21252215f8fc/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/MZBannerView-v2.0.2.aar/e21bcdf5746ff7ac4528f63590db6c18/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/MZBannerView-v2.0.2.aar/e21bcdf5746ff7ac4528f63590db6c18/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.7/751f548c85fa49f330cecbb1875893f971b33c4e/gson-2.7.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/crashlytics-core-2.6.5.aar/2ecde2edc87dec29ef8505b6251e1391/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-flags-16.0.1.aar/a73a0e23d7c46a78a79b3ed00d624179/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-measurement-base-16.0.4.aar/53f387bded267402d51d802b94f61880/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.14/775b7e22fb10026eed3f86e8dc556dfafe35f2d5/animal-sniffer-annotations-1.14.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/recyclerview-v7-27.1.1.aar/8845844df3df9695051e1e803271e35d/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/recyclerview-v7-27.1.1.aar/8845844df3df9695051e1e803271e35d/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-context/1.12.0/5b63a170b786051a42cce08118d5ea3c8f60f749/grpc-context-1.12.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-measurement-connector-impl-17.0.3.aar/1eba78f02b0296c9ec1aa005f93f44a6/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-storage-16.0.5.aar/346c99a70ebe93254b36e9f91925fd59/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-media-compat-27.1.1.aar/4d6f9dec78219b4e909ef0a7b856d210/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-media-compat-27.1.1.aar/4d6f9dec78219b4e909ef0a7b856d210/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/multidex-1.0.3.aar/68cd6490c0865de0f1ce20d5bc3c447d/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-core-ui-27.1.1.aar/88165d9e3e818fc4baed65554f401163/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-core-ui-27.1.1.aar/88165d9e3e818fc4baed65554f401163/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.3.aar/1ef3322acd1153abf1b4e7b12a280bd8/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.3.aar/1ef3322acd1153abf1b4e7b12a280bd8/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-base-16.0.1.aar/075016d5c74dc3d1dd986eb89a3dd0e1/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-base-16.0.1.aar/075016d5c74dc3d1dd986eb89a3dd0e1/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-database-collection-16.0.1.aar/3f7c369701689fb97c828a4b89a79e5b/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.1/976d8d30bebc251db406f2bdb3eb01962b5685b3/j2objc-annotations-1.1.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-fragment-27.1.1.aar/b9984dcb6f6340fbc8ede3fe70644c60/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-protobuf-lite/1.12.0/f5bebfbd5e93b8bbb58888a5cfaa9f490fb7b455/grpc-protobuf-lite-1.12.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-auth-interop-16.0.1.aar/c5fa5058b59a7aa33c40ca969dba1862/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/runtime-1.1.0.aar/9d9e15e816da554f218bdbb4050011ea/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/beta-1.2.10.aar/ad3fa669cc5af3d318a3f674c6922f77/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/design-27.1.1.aar/77576f590cb72c315236be9d769f9efe/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/design-27.1.1.aar/77576f590cb72c315236be9d769f9efe/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/multidex-instrumentation-1.0.2.aar/1d6fac740b32e88cb2afc26579900c86/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/c11b54c3d0792044f4c20dbd6ba6e6b5/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/c11b54c3d0792044f4c20dbd6ba6e6b5/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/badgeview-1.1.3.aar/053e28243661fc2cb64a0986f611fdb2/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/badgeview-1.1.3.aar/053e28243661fc2cb64a0986f611fdb2/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/fabric-1.4.5.aar/434c19dca36473efa79429b04b1e1399/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-lite/3.0.1/59b5b9c6e1a3054696d23492f888c1f8b583f5fc/protobuf-lite-3.0.1.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.android.support.constraint/constraint-layout-solver/1.1.3/bde0667d7414c16ed62d3cfe993cff7f9d732373/constraint-layout-solver-1.1.3.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/runtime-1.1.0.aar/d83c9ca5cb3737a32fb643025d6a4f7e/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/transition-27.1.1.aar/9c32f38e973c663fe039ad77e0ad748e/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/transition-27.1.1.aar/9c32f38e973c663fe039ad77e0ad748e/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-auth-16.0.5.aar/63d201997b014cd932f86057909fa81f/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-measurement-connector-17.0.1.aar/d2c97032f2dbc70fbb3aa488c1c89105/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/butterknife-8.8.0.aar/dd7dac8dda0e406b365a38351466ab46/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.android.support/support-annotations/27.1.1/39ded76b5e1ce1c5b2688e1d25cdc20ecee32007/support-annotations-27.1.1.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/cardview-v7-27.1.1.aar/356278dd9d8026e14d403aa64dab18cc/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/cardview-v7-27.1.1.aar/356278dd9d8026e14d403aa64dab18cc/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.opencensus/opencensus-contrib-grpc-metrics/0.11.0/d57b877f1a28a613452d45e35c7faae5af585258/opencensus-contrib-grpc-metrics-0.11.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/animated-vector-drawable-27.1.1.aar/5f57c06994c484a924e76e4da8c67f94/jars/classes.jar
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/libs/mail.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-ads-identifier-16.0.0.aar/691626876e12e39f56263ba959bc98f6/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-compat-27.1.1.aar/249900c7af24be072817499d68c5479f/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-compat-27.1.1.aar/249900c7af24be072817499d68c5479f/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.13.0/a9283170b7305c8d92d25aff02a6ab7e45d06cbe/okio-1.13.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-measurement-api-16.0.3.aar/73829d8e70d3aecfb5e94d99da18427a/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/viewmodel-1.1.0.aar/7e7ab23a2153d715cbca7d2c9fdbee21/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-stats-16.0.1.aar/3a455cfa625a6e80ca5263f2e23cd214/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-vector-drawable-27.1.1.aar/6a1628ac2a7a43815d57fab3967cac2c/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-basement-16.1.0.aar/2dafbd0bde94286338c8e10841a43fcc/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/play-services-basement-16.1.0.aar/2dafbd0bde94286338c8e10841a43fcc/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/support-core-utils-27.1.1.aar/7fafc1b41356ee8e1cadfb3805c3ae03/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.0/5871fb60dc68d67da54a663c3fd636a10a532948/jsr305-3.0.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/LikeButton-0.2.3.aar/ba550f0e115fcc8a1b11e248de83dcf5/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/LikeButton-0.2.3.aar/ba550f0e115fcc8a1b11e248de83dcf5/res/
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/22.0/3564ef3803de51fb0530a8377ec6100b33b0d073/guava-22.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/protolite-well-known-types-16.0.1.aar/bdfbf611addecc5ca80973e36c153b3b/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.12.0/541a5c68ce85c03190e29bc9e0ec611d2b75ff24/grpc-core-1.12.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-firestore-17.1.3.aar/fd8376ec33d52550b992cd5c78618cf8/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-okhttp/1.12.0/3fdb2c85587702865b464b2f6faabf7e2e294a3d/grpc-okhttp-1.12.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/crashlytics-2.9.6.aar/7d835bae17379b57b11a4aa90d4b52a6/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.squareup.picasso/picasso/2.5.2/7446d06ec8d4f7ffcc53f1da37c95f200dcb9387/picasso-2.5.2.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/livedata-core-1.1.0.aar/521172cac4b3551b2bed0d59df02272a/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-iid-interop-16.0.1.aar/1e64954cbeed70c4af89f9dc6cfb1a94/jars/classes.jar
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/libs/activation.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/android.arch.core/common/1.1.0/8007981f7d7540d89cd18471b8e5dcd2b4f99167/common-1.1.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/answers-1.4.4.aar/6db254e8879b8579f4796930b44a812a/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-stub/1.12.0/fbd2bafe09a89442ab3d7a8d8b3e8bafbd59b4e0/grpc-stub-1.12.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-analytics-impl-16.2.3.aar/35b6ff4a71bc42a0f4252da598431261/jars/classes.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife-annotations/8.8.0/b258209549457d03e912ec4641735fc88048df99/butterknife-annotations-8.8.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/modules-2/files-2.1/io.opencensus/opencensus-api/0.11.0/c1ff1f0d737a689d900a3e2113ddc29847188c64/opencensus-api-0.11.0.jar
DEBUG: ExampleUnitTest: /C:/Users/User/.gradle/caches/transforms-1/files-1.1/firebase-iid-17.0.3.aar/09137ed01e054fb0624b00ffb690768a/jars/classes.jar
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/build/intermediates/sourceFolderJavaResources/test/debug
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/build/intermediates/sourceFolderJavaResources/debug
DEBUG: ExampleUnitTest: /D:/Android%20workspace/Custom-In/app/build/generated/mockable-android-27.v3.jar
```

**Comment by samtstern** [comment] 2018-12-14 19:38
@superdiazzz thank you for following up and sharing that you were able too solve this issue by disabling Instant Run.  You shouldn't have to do this, but it's good to know.

**Comment by samtstern** [comment] 2018-12-14 19:38
Closing because it doesn't have to do with FIrebaseUI.

**Closed by samtstern** 2018-12-14 19:38 UTC
