### ISSUE TITLE
FirebaseUI Auth  and Facebook SDK Error on running

### ISSUE THREAD

**Issue by moheny** [firebase/FirebaseUI-Android#230] opened 2016-08-01 20:21 UTC
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: __Nexus 5x___
  * Android OS version: __6___
  * Google Play Services version: __3.0.0___
  * Firebase/Play Services SDK version: ___9.4.0__
  * FirebaseUI version: __0.4.4__
  
### Step 3: Describe the problem:
After Compiling the firebaseUI and Facebook sdk i'm getting this error:

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from [com.facebook.android:facebook-android-sdk:4.14.0] AndroidManifest.xml:32:13-72
  	is also present at [com.firebaseui:firebase-ui-auth:0.4.4] AndroidManifest.xml:68:13-58 value=(@style/FirebaseUI.Translucent).
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:29:9-32:75 to override.

#### Steps to reproduce:

I don't undersaynd the tools:replace suggestion

**Comment by samtstern** [comment] 2016-08-01 20:34
@moheny what version of the Facebook SDK are you using?  Can you show your `build.gradle` dependencies section?

**Comment by samtstern** [comment] 2016-08-01 20:39
Ah I see that you are using Facebook Android SDK 4.14.0.  But FirebaseUI already depends on version 4.11.0 of the SDK.  Can you try removing your Facebook dependency and just relying on the transitive dependency brought in by FirebaseUI?

**Comment by AndroidCollege** [comment] 2016-08-01 21:22
Yup, removing FirebaseUi Auth from the dependency fixing the problem, but is it no possible to use them both ? 
my build.gradle is : 
  compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'

    compile 'com.google.firebase:firebase-database:9.4.0'
    compile 'com.google.firebase:firebase-auth:9.4.0'
    compile 'com.google.android.gms:play-services-auth:9.4.0'
    compile 'com.firebaseui:firebase-ui-database:0.4.4'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'

**Comment by samtstern** [comment] 2016-08-01 21:24
I would remove `compile 'com.facebook.android:facebook-android-sdk:[4,5)'` and re-add `com.firebaseui:firebase-ui-auth:0.4.4`, which will bring the Facebook SDK in automatically.  I think the problem is that when you have both you have two versions of the Facebook SDK.

**Comment by AndroidCollege** [comment] 2016-08-01 21:26
I didn't know it's bringing the latest SDK of Facebook automatically ... Thank you for the info.

**Comment by samtstern** [comment] 2016-08-01 21:28
@moheny if it works when you remove Facebook and re-add FBUI, please close this issue.

**Comment by AndroidCollege** [comment] 2016-08-01 21:31
close

**Comment by AndroidCollege** [comment] 2016-08-01 21:37
closed

**Closed** 2016-08-01 22:48 UTC

**Comment by shyamwebb** [comment] 2017-12-22 04:11
But when i remove facebook SDK, its showing error 'facebook related SDK classes are not resolved.
