### ISSUE TITLE
Open this project in Android Studio

### ISSUE THREAD

**Issue by fleoparra** [firebase/FirebaseUI-Android#1380] opened 2018-06-29 14:21 UTC
When I try to open FirebaseUI-Android with Android Studio nothing happens.

I use Android studio 3.1.3. I want to see demos there.

https://github.com/firebase/FirebaseUI-Android.git

I have tried to open app project but nothing happens. All views show a message that said "Nothing to show".

Someone have opened this project with android studio? Thanks.

All other projects open without problems.

**Comment by samtstern** [comment] 2018-06-29 15:55
@fleoparra this looks like a duplicate of #1349 

You should:

- Clone or download the project
- In Android studio use "open from external model"

The reason for this is that we use the gradle kotlin extensions rather than regular gradle scripts, so Android Studio doesn't recognize it as a pure gradle project.

**Closed by samtstern** 2018-06-29 15:55 UTC
