### ISSUE TITLE
Separate theme for AuthUI: ChooseAccountActivity and RegisterEmailActivity

### ISSUE THREAD

**Issue by kyleparker** [firebase/FirebaseUI-Android#340] opened 2016-10-05 20:20 UTC
- Google Play Services version: 9.6.1
- Firebase/Play Services SDK version: 9.6.1
- FirebaseUI version: 0.6.0

This is a feature request/enhancement, rather than an issue. It would be nice to have two separate Themes for the ChooseAccountActivity and the other activities within the AuthUI library. The reason for this: from a UI perspective, I have our logo on the ChooseAccountActivity, which already contains the title of the app, along with a specific background color. So for this, I would want to use NoActionBar for the base theme (no need to repeat the title or have an extra space at the top of the screen). However, on the RegisterEmailActivity, it is helpful to have the toolbar with the title of the activity. Also, I would prefer to have a different background color on those sub-activities as compared to the main activity of the flow.

Otherwise, this is a great library and eliminates a lot of the code needed to get users signed into the app - thanks for creating this!

**Comment by moheny** [comment] 2016-10-09 20:55
Totally agree with you. 
I see no use in a seperate the different logins in a brand new activity.
In my case I have stop using firebaseUI since i have a tutorial guide when my app first load up, and then i need to point users to the Firebase activity which destroy my whole user experience...

**Comment by samtstern** [comment] 2017-07-20 20:55
Closing as duplicate of #229

**Closed by samtstern** 2017-07-20 20:55 UTC
Labels: enhancement, feature:auth
