### ISSUE TITLE
Issue with CountryListSpinner

### ISSUE THREAD

**Issue by wakim** [firebase/FirebaseUI-Android#1738] opened 2020-02-20 11:26 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Nexus 5X
  * Android OS version: 6.0.1
  * Google Play Services version: 4.3.3
  * Rooted device (Don't know any info on this)
  * Firebase/Play Services SDK version: 17.2.2
  * FirebaseUI version: 6.2.0
  
### Step 3: Describe the problem:

Seeing some users having issues when doing sign in with sms provider, the app is crashing when opening the activity.

Seems related with https://github.com/firebase/FirebaseUI-Android/issues/1734

#### Steps to reproduce:

1 - Users a getting in the sms login page
2 - App is crashing
  
#### Observed Results:

 ```
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
java.util.AbstractSet.removeAll (AbstractSet.java:99)
com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner (CountryListSpinner.java)
com.firebase.ui.auth.ui.phone.CountryListSpinner.access$002 (CountryListSpinner.java)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner (CheckPhoneNumberFragment.java)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.access$000 (CheckPhoneNumberFragment.java)
androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.FragmentManager.dispatchPrimaryNavigationFragmentChanged (FragmentManager.java)
androidx.fragment.app.FragmentManager.dispatchPause (FragmentManager.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.FragmentManager.addRetainedFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.attachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.attachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.detachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.detachFragment (FragmentManager.java)
androidx.fragment.app.FragmentController.attachHost (FragmentController.java)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1237)
android.app.Activity.performStart (Activity.java:6268)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2379)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2476)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```
  
#### Expected Results:

It should work without errors
  
#### Relevant Code:

```
AuthUI.getInstance()
            .createSignInIntentBuilder()
            .setAvailableProviders(listOf(AuthUI.IdpConfig.PhoneBuilder().build()))
            .build()

startActivityForResult(intent, RC_FIREBASE_LOGIN)
```

My workaround i'm using for now is to provide a list of whitelisted countries:

```
providers = listOf(
    AuthUI.IdpConfig.PhoneBuilder()
   .setWhitelistedCountries(listOf("+55"))
   .build()
)
AuthUI.getInstance()
            .createSignInIntentBuilder()
            .setAvailableProviders(providers)
            .build()

startActivityForResult(intent, RC_FIREBASE_LOGIN)
```

**Comment by samtstern** [comment] 2020-02-20 16:55
Duplicate of #1734

**Closed by samtstern** 2020-02-20 16:55 UTC
