### ISSUE TITLE
This app is not authorized to use Firebase Authentication in EMULATOR

### ISSUE THREAD

**Issue by thelong1EU** [firebase/FirebaseUI-Android#868] opened 2017-08-16 16:20 UTC
### Describe your environment

  * Android device: Pixel XL
  * Android OS version: Android O
  * Google Play Services version: just updated
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.2.0
  
### Describe the problem:
I'm getting this error when I try to run my app on emulator.

```
This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console.
 com.google.firebase.auth.FirebaseAuthException: This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device? ]
 at com.google.android.gms.internal.jz.zzK(Unknown Source:239)
 at com.google.android.gms.internal.kp.zza(Unknown Source:2)
 at com.google.android.gms.internal.kq.run(Unknown Source:37)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6541)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
  
#### What I did:
1. I have the Play Store updated.
2. I've added all the SHA-1 code to Firebase console and the package name matches.
3. In fact when I run the app on a real device it runs perfectly and I can login.

**Comment by krisu7** [comment] 2017-08-16 17:40
@thelong1EU It says in log you provided: 

> [ App validation failed. Is app running on a physical device? ]

I don't know for sure, but it may be related to #790 and done to prevent fraud and abuse.

**Comment by samtstern** [comment] 2017-08-17 15:22
@thelong1EU are you trying to do Phone Authentication? That will not work on the emulator.

**Comment by thelong1EU** [comment] 2017-08-17 15:27
Yes! Thanks for the answer. Do you know a link where this is documented?

**Comment by samtstern** [comment] 2017-08-17 16:52
https://firebase.google.com/docs/auth/android/phone-auth

> "Also, note that phone number sign-in requires a physical device and won't work on an emulator."

I agree this could be called out a little clearer.  Closing this issue since FirebaseUI is working as intended here.

**Closed by samtstern** 2017-08-17 16:52 UTC

**Comment by arpit7997** [comment] 2017-12-05 11:26
I have the correct SHA 1 certificate and project name as Google maps is working fine on my app. Still I'm getting this error. Please help

**Comment by adirzoari** [comment] 2018-05-01 09:53
did you find any solution?
