### ISSUE TITLE
High crash rate (NPE) acessing com.firebase.ui.auth.AuthUI.getInstance

### ISSUE THREAD

**Issue by RuiVarela** [firebase/FirebaseUI-Android#1126] opened 2018-01-25 08:41 UTC
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment
  * Android device: Several
  * Android OS version: 4, 5, 6
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.0
  
### Step 3: Describe the problem:
Hi All,
we are currently experiencing an high crash rate using firebase ui,
the current snippet

```
      m_activity.startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setIsSmartLockEnabled(false)
                        .setAvailableProviders(Arrays.asList(new AuthUI.IdpConfig.PhoneBuilder().build()))
                        .build(),
                REQUEST_LOGIN_PHONE);
```

produces erratically the following issue, 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzdd)' on a null object reference
       at com.google.android.gms.internal.zzdvv.zzb(Unknown Source)
       at com.google.android.gms.internal.zzdwc.setFirebaseUIVersion(Unknown Source)
       at com.google.firebase.auth.FirebaseAuth.signOut(Unknown Source)
       at com.firebase.ui.auth.AuthUI.(AuthUI.java)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:244)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:232)
       at co.triller.droid.Activities.Login.LoginController.connectPhone(LoginController.java:1280)
       at co.triller.droid.Activities.Main.SplashLoginFragment$4.onClick(SplashLoginFragment.java:104)
       at android.view.View.performClick(View.java:5721)
       at android.view.View$PerformClick.run(View.java:22620)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
here is the more detailed info from crashlitics
http://crashes.to/s/a80689a7452

this issue is out top crash with an impact of 0.27% on out app,
any advice, or workaround for this?

**Comment by vanleeuwenbram** [comment] 2018-01-25 12:35
some extra info in the issue that already exists:
https://github.com/firebase/FirebaseUI-Android/issues/1104

**Comment by samtstern** [comment] 2018-01-25 16:12
This is a duplicate of #1104, let's discuss there.

**Closed by samtstern** 2018-01-25 16:12 UTC
