### ISSUE TITLE
FirebaseArray's Limited Access Modifiers

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#337] opened 2016-10-03 00:34 UTC
I'm trying to create an addon to FirebaseUI; this addon includes the FirebaseSpinnerAdapter I proposed in #304 for this library. @puf suggested I put it in a separate library, thus I created the [FirebaseUI-Android-Addons repository](https://github.com/TheCraftKid/FirebaseUI-Android-Addons). 
It (for now) includes the FirebaseSpinnerAdapter, but I ran into a problem during implementation: I had to create a [copy of the FirebaseArray](https://github.com/TheCraftKid/FirebaseUI-Android-Addons/blob/v0.1.0/library/src/main/java/com/craft/libraries/firebaseuiaddon/FirebaseArray.java) for a future feature since the one FirebaseUI provides is package-private.

I was wondering if I could submit a PR to change that since my problem would be fixed with some SOLID programming.

**Comment by SUPERCILEX** [comment] 2016-10-08 21:13
@puf I don't see the harm in making `FirebaseArray` public. `mSnapshots` is still private so I don't see how using `FirebaseArray` could lead to unexpected behavior.

**Comment by puf** [comment] 2016-10-09 07:13
You can currently use FirebaseArray in your own adapters by putting them in
the same package, which is how FirebaseUI's adapters do it.

We've so far steered away from making `FirebaseArray` part of the public
contract of the library. The reasoning is that we'd be supporting its API
contract and guaranteeing backwards compatibility. While we may (and
probably should) at some point do that, I'd prefer to push that moment out
a bit further if possible.

**Comment by samtstern** [comment] 2017-03-06 03:27
#544 has been merged.  You can check out the `version-2.0.0-dev` branch and play around if you're curious.

**Comment by TheCraftKid** [comment] 2017-03-06 03:35
Thanks!

**Closed** 2017-06-12 16:55 UTC
Labels: feature:database, fix-implemented
