### ISSUE TITLE
Crash in setFirebaseUIVersion()

### ISSUE THREAD

**Issue by dimipaun** [firebase/FirebaseUI-Android#1141] opened 2018-02-07 15:31 UTC
We are seeing this crash in Crashlytics:
`
Fatal Exception: java.lang.NullPointerException
       at com.google.android.gms.internal.zzdvv.zzb(Unknown Source)
       at com.google.android.gms.internal.zzdwc.setFirebaseUIVersion(Unknown Source)
       at com.google.firebase.auth.FirebaseAuth.setFirebaseUIVersion(Unknown Source)
       at com.firebase.ui.auth.AuthUI.(AuthUI.java:208)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:244)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:232)
`
The device is running Android 4.4.2.

**Comment by samtstern** [comment] 2018-02-07 15:49
Duplicate of #1126

**Closed by samtstern** 2018-02-07 15:49 UTC
