### ISSUE TITLE
Continue as guest icon issue

### ISSUE THREAD

**Issue by lsirac** [firebase/FirebaseUI-Android#1376] opened 2018-06-26 22:03 UTC
For the pathData value we get a lint error: "Use 0.94 instead of .94 to avoid crashes on some devices."

This is for the "2.1.94" portion. I've tried "2.0.94" and "2.10.94" - can't seem to get rid of it.

**Comment by samtstern** [comment] 2018-06-27 00:10
@lsirac are we worried about this anymore?  Seems like the `lint-baseline` worked and it's just a bad regex, right? 

Might want to file a bug against Android Link folks though.

**Comment by IvanBean** [comment] 2018-09-21 07:21
Hi,

Not sure whether my issue belongs to here, but one of our tablet crash due to the guest icon, information as following:

 * Android device: Asus ME572C
 * Android OS version: 5.0.1
 * FirebaseUI version: 4.2.0

Log from Crashlytics:
`
SupportVectorDrawablesButton.java line 58
com.firebase.ui.auth.util.ui.SupportVectorDrawablesButton.initSupportVectorDrawablesAttrs
`

`
Caused by java.lang.NumberFormatException: Invalid float: "2.1.94"
                    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
                    at java.lang.StringToReal.initialParse(StringToReal.java:160)
                    at java.lang.StringToReal.parseFloat(StringToReal.java:323)
                    at java.lang.Float.parseFloat(Float.java:306)
                    at android.util.PathParser.getFloats(PathParser.java:178)
                    at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
                    at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
                    at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
                    at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
                    at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
                    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
                    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
                    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2442)
                    at android.content.res.Resources.loadDrawable(Resources.java:2354)
                    at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
                    at com.firebase.ui.auth.util.ui.SupportVectorDrawablesButton.initSupportVectorDrawablesAttrs(SupportVectorDrawablesButton.java:58)
                    at com.firebase.ui.auth.util.ui.SupportVectorDrawablesButton.(SupportVectorDrawablesButton.java:31)
                    at java.lang.reflect.Constructor.newInstance(Constructor.java)
                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                    at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                    at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                    at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.populateIdpList(AuthMethodPickerActivity.java:236)
                    at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onCreate(AuthMethodPickerActivity.java:92)
                    at android.app.Activity.performCreate(Activity.java:5975)
                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
                    at android.app.ActivityThread.access$800(ActivityThread.java:147)
                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                    at android.os.Handler.dispatchMessage(Handler.java:102)
                    at android.os.Looper.loop(Looper.java:135)
                    at android.app.ActivityThread.main(ActivityThread.java:5264)
                    at java.lang.reflect.Method.invoke(Method.java)
                    at java.lang.reflect.Method.invoke(Method.java:372)
                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
`

Other two Asus tablets we tested works fine, any reply will be appreciated.

**Comment by IvanBean** [comment] 2018-09-21 17:44
The other two are Asus Z500M on Android 7.1 and Sony Xperia Z3C on Android 6.0, not both Asus tablet, my mistake!

**Comment by samtstern** [comment] 2018-09-21 18:44
@IvanBean thanks!  I suspect that we'll need to use Android 5.0 to reproduce this, which is why I asked.

**Comment by samtstern** [comment] 2018-10-24 14:19
This has been fixed and released in version `4.2.1`.

**Closed by samtstern** 2018-10-24 14:19 UTC
Labels: fix-implemented

**Comment by IvanBean** [comment] 2018-10-25 03:57
Thanks! It works now.
