### ISSUE TITLE
NullPointerException in EmailLinkErrorRecoveryActivity's onCreate.

### ISSUE THREAD

**Issue by ranjan-malav** [firebase/FirebaseUI-Android#1729] opened 2020-01-26 15:20 UTC
### Step 2: Describe your environment:
  * Android device: Nexus 4
  * Android OS version: 6.0.1
  * Google Play Services version: 4.3.3
  * Firebase/Play Services SDK version: core:17.2.2, auth:19.2.0
  * FirebaseUI version: 4.3.1
  
### Step 3: Describe the problem:

I have Email, phone and Gmail sign-in functionality in the app. I'm not sure how to reproduce the bug but might have some idea why it happened.
While creating `AuthUI` instance, I don't provide any style to the builder and one of the users somehow reached `EmailLinkErrorRecoveryActivity`. And in that activity, super `AppCompatBase` activity's `onCreate` method got called which in turn set the theme by calling `getFlowParams` method, which tries to get `FlowParameters` from the intent.
But since `HelperActivityBase` has null check while creating the intent, I believe the problem is caused by `KickoffActivity`'s `invalidateEmailLink` method.

#### Steps to reproduce:

Call `KickoffActivity`'s `invalidateEmailLink` method without providing the theme to the `AuthUI` instance `SignInIntent`  builder (this is an educated guess, I'm not sure how to call this method locally).
  
#### Observed Results:

App crashed.
I tried deobfucating the stack trace but it returned the same thing. I have mapping file uploaded to Play console and also have tried `retrace` tool but it is not working. Stack trace - 
```
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.data.model.b.c' on a null object reference
       at com.firebase.ui.auth.ui.a.onCreate(AppCompatBase.java:32)
       at com.firebase.ui.auth.ui.email.EmailLinkErrorRecoveryActivity.onCreate(EmailLinkErrorRecoveryActivity.java:36)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
  
#### Expected Results:

App not to crash even if no theme is provided.
  
#### Relevant Code:

  ```
startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setAvailableProviders(providers)
                                    .build(),
                            RC_SIGN_IN);
  ```

**Comment by samtstern** [comment] 2020-01-31 23:38
@ranjan-malav thanks for reporting this!  As you said it's a duplicate of #1650 so I am going to close it but I will copy your very helpful comments over there.

**Closed by samtstern** 2020-01-31 23:38 UTC
