### ISSUE TITLE
NPE on .keepSynced(true);

### ISSUE THREAD

**Issue by matuzenko88** [firebase/FirebaseUI-Android#10] opened 2015-08-26 10:46 UTC
When I try to set .keepSynced(true); I'm getting Null Pointer Exception which crash my app. Please see detailed log

Process: za.co.swarmapps.kauai, PID: 8307
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.firebase.client.snapshot.ChildKey.equals(java.lang.Object)' on a null object reference
            at com.firebase.client.Query.keepSynced(Query.java:211)

compileSdkVersion 22
buildToolsVersion "23.0.0"
Library version compile 'com.firebase:firebase-client-android:2.3.1'

**Comment by puf** [comment] 2015-08-26 12:56
Hi Oleksander,

From your description it sounds like this is not related to the
FirebaseUI-Android open source project, but to the Firebase for Android SDK.

If so, can you create a minimal project that reproduces the problem and
send that to support@firebase.com?

Thanks,
            Frank

**Comment by puf** [comment] 2015-08-26 15:12
Our API team was able to reproduce the problem. It will be fixed in the nexy release of the Android and iOS SDKs. Since it is indeed not related to this repo, I'm closing the issue here.

**Closed by puf** 2015-08-26 15:12 UTC

**Comment by matuzenko88** [comment] 2015-08-26 16:10
Many thanks!
