### ISSUE TITLE
Crash with password saved on Google Smart Lock

### ISSUE THREAD

**Issue by Fax3D** [firebase/FirebaseUI-Android#144] opened 2016-05-26 12:48 UTC
I'm having an issue if i save the password with Google smart lock. The second time i try to login (email+password) into my app, the Firebase ui flow crash... only after erasing password on passwords.google.com i can login without problem.

Here the stacktrace:

Class not found when unmarshalling: com.firebase.ui.auth.ui.FlowParameters
                                        java.lang.ClassNotFoundException: com.firebase.ui.auth.ui.FlowParameters
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.Class.forName(Class.java:324)
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                            at android.os.Parcel.readParcelable(Parcel.java:2358)
                                            at android.os.Parcel.readValue(Parcel.java:2264)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.BaseBundle.getString(BaseBundle.java:920)
                                            at android.content.Intent.getStringExtra(Intent.java:6183)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6319)
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6097)
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990)
                                            at android.os.Binder.execTransact(Binder.java:453)
                                         Caused by: java.lang.ClassNotFoundException: com.firebase.ui.auth.ui.FlowParameters
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:324) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                            at android.os.Parcel.readValue(Parcel.java:2264) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                            at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                            at android.content.Intent.getStringExtra(Intent.java:6183) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6319) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6097) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990) 
                                            at android.os.Binder.execTransact(Binder.java:453)

**Comment by Fax3D** [comment] 2016-06-01 15:14
Someone could check this issue please?

Thanks!

**Comment by katowulf** [comment] 2016-06-01 17:27
Not sure we can help here. We don't use smart lock much and don't have much experience with this. `Caused by: java.lang.ClassNotFoundException: com.firebase.ui.auth.ui.FlowParameters` suggests that there is an incorrectly configured intent, but there are a lot of reasons you could see this, and not nearly enough info here to help you troubleshoot.

**Comment by puf** [comment] 2016-06-01 19:07
@iainmcgin can you weigh in here?

**Comment by tsadoklf** [comment] 2016-08-17 12:13
Crashed with the same exception

**Comment by stevedj** [comment] 2016-09-14 02:06
same here

**Comment by amandle** [comment] 2016-10-16 22:51
@Fax3D @stevedj @tsadoklf From the stack trace it seems to be a classloader issue, but I am unable to reproduce it either on Android M or on KitKat.  Can anyone confirm that it is still an issue on the latest FirebaseUI 0.6.1?  Thanks!

**Comment by amandle** [comment] 2016-10-21 20:37
closing as I am unable to reproduce this, please comment if it is still happening for you!

**Closed by amandle** 2016-10-21 20:37 UTC
Labels: bug, feature:auth

**Comment by riddy6421** [comment] 2017-01-31 13:46
Still Happening to me same issue.

**Comment by ahaverty** [comment] 2017-02-07 16:32
I hit the same exception today, I believe I fixed it by ensuring my firebaseUI matched the appropriate firebase versions found on the readme https://github.com/firebase/FirebaseUI-Android (Currently UI v1.1.1 should be using either firebase v10.0.0 or v10.0.1)
