### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.FragmentActivity.getSupportFragmentManager()' on a null object

### ISSUE THREAD

**Issue by j2emanue** [firebase/FirebaseUI-Android#1193] opened 2018-03-18 06:13 UTC
if you have a very poor network connection then try to call the following code from a fragment:

`private void ititFireBaseUi() {

        AuthUI.getInstance()
                .signOut(getActivity())
                .addOnCompleteListener(new OnCompleteListener<Void>() {
                    public void onComplete(@NonNull Task<Void> task) {
                        // Choose authentication providers
                        List<AuthUI.IdpConfig> providers = Arrays.asList(
                                new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build());
                        //new AuthUI.IdpConfig.Builder(AuthUI.TWITTER_PROVIDER).build());

// Create and launch sign-in intent
                        startActivityForResult(
                                AuthUI.getInstance()
                                        .createSignInIntentBuilder()
                                        .setAvailableProviders(providers)
                                        .setLogo(R.drawable.myapp_logo)
                                        .build(),
                                RC_SIGN_IN);
                    }
                });

    }

` 
i get the following error and the application crashes:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.mobile.myapp.labs, PID: 7684
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.FragmentActivity.getSupportFragmentManager()' on a null object reference
                                                                          at com.firebase.ui.auth.util.signincontainer.IdpSignInContainer.signIn(IdpSignInContainer.java:61)
                                                                          at com.firebase.ui.auth.util.signincontainer.SignInDelegate.redirectToIdpSignIn(SignInDelegate.java:384)
                                                                          at com.firebase.ui.auth.util.signincontainer.SignInDelegate.handleCredential(SignInDelegate.java:264)
                                                                          at com.firebase.ui.auth.util.signincontainer.SignInDelegate.onComplete(SignInDelegate.java:164)
                                                                          at com.google.android.gms.tasks.zzf.run(Unknown Source)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by SUPERCILEX** [comment] 2018-03-18 06:17
Yep, duplicate of https://github.com/firebase/FirebaseUI-Android/issues/1181. The next release will include a fix it all goes well.

**Closed** 2018-03-18 06:19 UTC
