### ISSUE TITLE
Remove previous callbacks for wrong number entered.

### ISSUE THREAD

**Issue by quantumInfection** [firebase/FirebaseUI-Android#1396] opened 2018-07-20 07:39 UTC
### Step 1: Are you in the right place?
Yes.
### Step 2: Describe your environment

  * Android device: Any
  * Android OS version: Any
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.1
  
#### Steps to reproduce:

  1. Enter wrong number.
  2. Enter another wrong number again.
  3. Enter correct number. 
  4. Wait for the Sms auto fill. First it shows 'Wrong code entered' and then logs in.
  
#### Observed Results:
  It generates 3 different callbacks for `onVerificationCompleted` for the first two callbacks `signInWithCredential` fails due to wrong number and it goes to success for the last one.

  
#### Expected Results:
  It should auto cancel all previous callbacks or there should a way to cancel previous callbacks.

**Comment by SUPERCILEX** [comment] 2018-07-20 07:40
Can you try with FUI v4.1.0? We fixed tons of bugs in that area.

**Comment by quantumInfection** [comment] 2018-07-20 07:42
I'll get back to you asap.

**Comment by quantumInfection** [comment] 2018-07-20 08:48
@SUPERCILEX Issue persists in FUI v4.1.0. Just tested.

**Comment by ismail-a-khan** [comment] 2018-07-20 08:53
@SUPERCILEX I think this is a Firebase Auth issue, not a Firebase UI issue.

**Comment by abdulwasae** [comment] 2018-07-20 09:09
I have made my own Firebase Authentication UI and I also face this issue. The `OnVerificationStateChangedCallbacks` get called for older, incorrect verification attempts, upon a correct attempt eventually.

I suspect the problem is with FirebaseAuth itself.

**Comment by samtstern** [comment] 2018-07-20 15:30
Trying to understand exactly what's going on here: are you saying that you get a bunch of `OnVerificationStateChangedCallbacks` all at once after the end of a series of requests?

**Comment by samtstern** [comment] 2018-07-23 00:46
@ismail-a-khan thanks for the very detailed steps! This sounds like a bug I should file with the Firebase Auth folks.  Because this is not a FirebaseUI issue I will close it here, but I will come back to this thread and update once I hear back from the Firebase Auth engineering team.

**Closed by samtstern** 2018-07-23 00:46 UTC

**Comment by quantumInfection** [comment] 2018-07-23 05:43
@ismail-a-khan Problem lies after `onVerificationCompleted`. All requests pass through `onVerificationCompleted` and whenever `FirebaseAuth.getInstance().signInWithCredential` is called it generates all callbacks including failed ones too. We should have a way to specify cancel previous `signInWithCredential`'s callbacks.

**Comment by ismail-a-khan** [comment] 2018-07-23 09:43
@samtstern, I think you might want to consider patching this in Firebase UI as well. You can work around the Firebase auth issue by doing the following:

1. Keep track of the 'current' phone number to verify, perhaps in an instance variable.
2. Immediately before you call `verifyPhoneNumber` (in the same method where you call it), save the 'current' phone number in a `final` local variable. Each callback can now reference a snapshot of the phone number that is being verified.
3. In the `onVerificationCompleted` method of the `OnVerificationStateChangedCallbacks` object that is passed to `verifyPhoneNumber`, check if the actual 'current' phone number to verify is equal to the phone number that was captured/enclosed by the callback object -- if the number's don't match, stop execution. Do the same in `onVerificationFailed` as well.


This should solve the problem, because now each `OnVerificationStateChangedCallbacks` is aware of which number it is trying to verify. By comparing the callback object's own number to the actual number that we want to verify, we can ignore all the callbacks that are associated with old numbers.


It's a bit of a hack, sure, but will at least solve the problem until the Firebase Auth team fixes the issue (which may take ages, given my experience with Cloud Firestore bugs...). If my explanation is not clear I could go ahead and submit a PR of the fix.


---------


Btw, I was slightly incorrect in my steps-to-recreate above. In step #6, it is actually `onVerificationCompleted` that is called, not `onVerificationFailed`, such that `onVerificationCompleted` is called twice overall. The fix is the same either way.

**Comment by Puneet1796** [comment] 2021-09-03 18:15
@samtstern Any update on the bug from Firebase-UI as well as from Firebase Auth?

**Comment by CarlosMesquita-Gorillas** [comment] 2021-12-22 11:17
@samtstern Having the same issue with those callbacks, any progress? Any updates?

**Comment by demolaf** [comment] 2026-05-14 15:59
Hello,

Thank you for taking the time to submit this bug.

We are happy to let you know that this has been resolved in **FirebaseUI for Android v10.0.0**, which is now available as a beta release. You can find the release notes [here](https://github.com/firebase/FirebaseUI-Android/releases/tag/10.0.0-beta02) and follow the [upgrade guide](https://github.com/firebase/FirebaseUI-Android/blob/master/docs/upgrade-to-10.0.md) to get started.

We will close this issue now. If you still experience this in the new version, please feel free to open a new issue.

Thank you again for your contribution.
