### ISSUE TITLE
Arraylist in FirebaseRecyclerview malfunctioning

### ISSUE THREAD

**Issue by adfaous** [firebase/FirebaseUI-Android#1671] opened 2019-09-12 09:53 UTC
Hello, 

I am building a forum view list inside my app with firebase recycler pagingadapter.  

https://ibb.co/h9FP2fv 

https://ibb.co/K5d4g2m

Please notice the changes in the two pictures above (on the tags), it happens whenever i scroll up and down the recyclerview. 

I dont know what is wrong, all others are working fine. 

Help

**Comment by adfaous** [comment] 2019-09-13 16:54
This is my binder 

`    adapter = new FirestorePagingAdapter<ForumModel, ForumViewHolder>(options) {
            @Override
            protected void onBindViewHolder(@NonNull ForumViewHolder forumViewHolder, int i, @NonNull ForumModel forumModel) {
                forumViewHolder.setPosttitle(forumModel.getPosttitle());
                forumViewHolder.setPosttcomment(forumModel.getPosttcomment());
                forumViewHolder.setPostdate(forumModel.getPostdate());
                forumViewHolder.setPostuserpix(forumModel.getPostuserpix());
                forumViewHolder.setPosttag(forumModel.getPosttag());

                forumViewHolder.forumContainer.setOnClickListener((View v) -> {
                    String positions = Objects.requireNonNull(getItem(i)).getId();
                    String postTime = TimeAgo.getTimeAgo(forumModel.getPostdate());
                    String posttc = String.valueOf(forumModel.getPosttcomment());
                    String postuv = String.valueOf(forumModel.getPostupvote());

                    Intent forumCommentActivity = new Intent(getContext(), ForumCommentActivity.class);
                    forumCommentActivity.putExtra("postposition", positions);
                    forumCommentActivity.putExtra("posttitle", forumModel.getPosttitle());
                    forumCommentActivity.putExtra("postcontent", forumModel.getPostcontent());
                    forumCommentActivity.putExtra("postdate", postTime);
                    forumCommentActivity.putExtra("posttcomment", posttc);
                    forumCommentActivity.putExtra("postuserid", forumModel.getPostuserid());
                    forumCommentActivity.putExtra("postupvote", postuv);
                    startActivity(forumCommentActivity);

                });
            }

            @NonNull
            @Override
            public ForumViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_forum_view, parent, false);
                return new ForumViewHolder(view);
            }


            @Override
            protected void onLoadingStateChanged(@NonNull LoadingState state) {
                switch (state) {
                    case LOADING_INITIAL:
                        forumShimmer.setVisibility(View.VISIBLE);
                        forumShimmer.startShimmerAnimation();
                        break;
                    case LOADING_MORE:
                        mSwipeRefreshLayout.setRefreshing(true);
                        break;
                    case LOADED:
                        forumShimmer.stopShimmerAnimation();
                        forumShimmer.setVisibility(View.GONE);
                        mSwipeRefreshLayout.setRefreshing(false);
                        break;
                    case FINISHED:
                        //            newsshimmer.stopShimmer();
                        //            newsshimmer.setVisibility(View.GONE);
                        //            newsList.setVisibility(View.VISIBLE);
                        mSwipeRefreshLayout.setRefreshing(false);
                        break;
                    case ERROR:
                        retry();
                        mSwipeRefreshLayout.setRefreshing(false);
                        break;
                }
            }


        };`


this is my getter 


` private class ForumViewHolder extends RecyclerView.ViewHolder {
        private View view;
        LinearLayout forumContainer;
        TextView postT, postD, postTc, tagA, tagB, tagC, tagD;
        ImageView postPp;

        ForumViewHolder(View itemView){
            super(itemView);
            view = itemView;
            forumContainer = view.findViewById(R.id.forumCardView);
        }

        void setPosttitle(String posttitle){
            postT = view.findViewById(R.id.list_forum_title);
            postT.setText(posttitle);
        }
        void setPostdate(long postdate) {
            postD = view.findViewById(R.id.forum_face_question_date);
            String postd = TimeAgo.getTimeAgo(postdate);
            postD.setText(postd);
        }
        void setPosttcomment(long posttcomment) {
            postTc = view.findViewById(R.id.forum_face_t_comment);
            String posttc = String.valueOf(posttcomment);
            postTc.setText(posttc);
        }
        void setPostuserpix(String postuserpix) {
            postPp = view.findViewById(R.id.forum_face_userphoto);
            if (postuserpix != null ) {
                Picasso.get()
                        .load(postuserpix)
                        .placeholder(R.drawable.com_facebook_profile_picture_blank_square)
                        .fit()
                        .into(postPp);
            }
        }
        void setPosttag(ArrayList<String> posttag) {
            int size = posttag.size();
            tagA = view.findViewById(R.id.forum_tag_a);
            tagB = view.findViewById(R.id.forum_tag_b);
            tagC = view.findViewById(R.id.forum_tag_c);
            tagD = view.findViewById(R.id.forum_tag_d);

            if (size == 2){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
            }else if(size == 3){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
            }else if(size == 4){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
                tagC.setVisibility(View.VISIBLE);
                tagC.setText(posttag.get(3));
            }else if(size == 5){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
                tagC.setVisibility(View.VISIBLE);
                tagC.setText(posttag.get(3));
                tagD.setVisibility(View.VISIBLE);
                tagD.setText(posttag.get(4));
            }

        }`

**Comment by adfaous** [comment] 2019-09-13 17:02
> Is there only one FirebaseRecyclerAdapter in the picture or does each item in the list have its own adapter to display the list of tags?
@samtstern only one sir. 

> I am 99% sure what is happening here is that you are failing to clear the tags properly when the view is recycled, or that you have a race condition between view recycling and tag loading.
Please help look at the code above, or a document that explain clearing the tags when the view is recycled

**Comment by samtstern** [comment] 2019-09-13 21:52
@adfaous I think the problem is here:

```
void setPosttag(ArrayList<String> posttag) {
            int size = posttag.size();
            tagA = view.findViewById(R.id.forum_tag_a);
            tagB = view.findViewById(R.id.forum_tag_b);
            tagC = view.findViewById(R.id.forum_tag_c);
            tagD = view.findViewById(R.id.forum_tag_d);

            if (size == 2){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
            }else if(size == 3){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
            }else if(size == 4){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
                tagC.setVisibility(View.VISIBLE);
                tagC.setText(posttag.get(3));
            }else if(size == 5){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
                tagB.setVisibility(View.VISIBLE);
                tagB.setText(posttag.get(2));
                tagC.setVisibility(View.VISIBLE);
                tagC.setText(posttag.get(3));
                tagD.setVisibility(View.VISIBLE);
                tagD.setText(posttag.get(4));
            }
```

Remember that views are *recycled* so you can't assume all the tags are `INVISIBLE` to start.

For instance you have:

```java
 if (size == 2){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));
}
```

But I think it needs to be:
```java
 if (size == 2){
                tagA.setVisibility(View.VISIBLE);
                tagA.setText(posttag.get(1));

                // Add these, you can choose GONE or INVISIBLE
                tagB.setVisibility(View.GONE);
                tagC.setVisibility(View.GONE);
                tagD.setVisibility(View.GONE);
}
```

**Comment by samtstern** [comment] 2019-09-13 21:53
I am going to close this issue as I am 99% sure this is not a bug in FirebaseUI.

**Closed by samtstern** 2019-09-13 21:53 UTC
Labels: needs-attention
