### ISSUE TITLE
Cannot create PhoneAuthCredential without either verificationProof, sessionInfo, ortemprary proof

### ISSUE THREAD

**Issue by chitra-bahadur** [firebase/FirebaseUI-Android#1648] opened 2019-06-24 05:19 UTC
#1392  @samtstern 

`Fatal Exception: java.lang.IllegalArgumentException: Cannot create PhoneAuthCredential without either verificationProof, sessionInfo, ortemprary proof.
       at com.google.android.gms.common.internal.Preconditions.checkArgument(Preconditions.java:35)
       at com.google.firebase.auth.PhoneAuthCredential.(SourceFile:5)
       at com.google.firebase.auth.PhoneAuthProvider.getCredential(PhoneAuthProvider.java:33)
       at com.retranzinfolabs.superzopordering.activities.LoginActivity.showOtpDialog(LoginActivity.java:497)
       at com.retranzinfolabs.superzopordering.activities.LoginActivity.onClick(LoginActivity.java:356)
       at android.view.View.performClick(View.java:5293)
       at android.view.View$PerformClick.run(View.java:21653)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:227)
       at android.app.ActivityThread.main(ActivityThread.java:6102)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)`

--------------------------------
Devices
---------------------------------
HTC Desire 10 pro
Redmi Note 5A
Galaxy A4
Galaxy J5(2016)
Galaxy J2
Galaxy J6
Galaxy J7
vivo
oppo A33f
Huawei Glory 9
-----------------------------------
Operating Systems
-----------------------------------
5.1.1
6.0
6.0.1
7.0
7.1.1
7.1.2
8.0.0

_Originally posted by @chitra-bahadur in https://github.com/firebase/FirebaseUI-Android/issues/1392#issuecomment-501998367_

**Comment by samtstern** [comment] 2019-06-25 20:23
Closing as a duplicate of #1392

**Closed by samtstern** 2019-06-25 20:23 UTC
