### ISSUE TITLE
CountryListSpinner.java:108 (Caused by java.lang.NullPointerException )

### ISSUE THREAD

**Issue by colorgold** [firebase/FirebaseUI-Android#1734] opened 2020-02-09 17:10 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _Nexus 5X____
  * Android OS version: _6.0.1____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _17.0.0____
  * FirebaseUI version: __4.3.2__
  
### Step 3: Describe the problem:
```
Unable to start activity ComponentInfo{app.myandroidhello.com.chatmurcianys/com.firebase.ui.auth.ui.phone.PhoneActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
```
#### Steps to reproduce:
I have not been able to reproduce the problem, but it only seems to happen to a Nexus phone
  
#### Observed Results:

```
  * Caused by java.lang.NullPointerException 
Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
keyboard_arrow_up 

java.util.AbstractSet.removeAll (AbstractSet.java:99) 
arrow_right 
com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner (CountryListSpinner.java:108) 

com.firebase.ui.auth.ui.phone.CountryListSpinner.init (CountryListSpinner.java:80) 

com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner (CheckPhoneNumberFragment.java:203) 

com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.onViewCreated (CheckPhoneNumberFragment.java:103) 

androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:892) 
```

#### Expected Results:

  * App crashes when selecting country in spinner (using pre-built UI phoneBuilder)
  
#### Relevant Code:

  ```
startActivityForResult(
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(phoneProvider)
                            .setTheme(R.style.BlankTheme)
                            .build(),REQUEST_SIGN_IN
            );
  ```

**Comment by samtstern** [comment] 2020-02-11 00:28
@colorgold thanks for filing this.  FirebaseUI `4.3.2` is almost a year old (released 03/26/2019) so we can no longer really accept bug reports from that version (especially if they are hard to replicate locally).  The latest version is `6.2.0`.  Can you try upgrading your app to a later version of the library and see if you still experience this issue?

**Comment by colorgold** [comment] 2020-02-12 20:57
> 6.2.0

I don't even know where I found the 4.3.2 version, but I also could not find the 6.2.0 version on the Firebase website. I have gone ahead and updated it. So far, the issue has not come up again. Thank you!

**Comment by samtstern** [comment] 2020-02-12 22:50
@colorgold oops looks like we had an outdated docs page somewhere.  We're gonna fix that ASAP.

**Comment by wakim** [comment] 2020-02-20 11:19
Hey folks, i'm getting the same error with the version 6.2.0. So far, 16 users are getting affected. I'm just seeing Android 6.0.1 and Nexus 6X having this problem.

Not sure if this could be the problem: https://github.com/firebase/FirebaseUI-Android/blob/9655063940c40dca18ce63796d4678564880c9e8/auth/src/main/java/com/firebase/ui/auth/ui/phone/CountryListSpinner.java#L93

But that if condition seems a little strange for me.

Below some more information about the error.

```
java.util.AbstractSet.removeAll (AbstractSet.java:99)
com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner (CountryListSpinner.java)
com.firebase.ui.auth.ui.phone.CountryListSpinner.access$002 (CountryListSpinner.java)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner (CheckPhoneNumberFragment.java)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.access$000 (CheckPhoneNumberFragment.java)
androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.FragmentManager.dispatchPrimaryNavigationFragmentChanged (FragmentManager.java)
androidx.fragment.app.FragmentManager.dispatchPause (FragmentManager.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java)
androidx.fragment.app.FragmentManager.addRetainedFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.attachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.attachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.detachFragment (FragmentManager.java)
androidx.fragment.app.FragmentManager.detachFragment (FragmentManager.java)
androidx.fragment.app.FragmentController.attachHost (FragmentController.java)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1237)
android.app.Activity.performStart (Activity.java:6268)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2379)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2476)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

I'm calling the AuthUI like this:
```
AuthUI.getInstance()
            .createSignInIntentBuilder()
            .setAvailableProviders(listOf(AuthUI.IdpConfig.PhoneBuilder().build()))
            .build()
startActivityForResult(intent, RC_FIREBASE_LOGIN)
```

**Comment by samtstern** [comment] 2020-02-20 16:56
Looks like @wakim has this issue on `6.2.0` so reopening.

**Comment by samtstern** [comment] 2020-03-25 17:49
The fix for this issue has been released in version `6.2.1`

**Closed by samtstern** 2020-03-25 17:49 UTC
Labels: auth, fix-implemented, type: bug

**Comment by deltaguita** [comment] 2020-04-17 09:54
Still happen on 6.2.1 
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'boolean java.util.Set.isEmpty()' on a null object reference
com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner (CountryListSpinner.java:93)

**Comment by wakim** [comment] 2020-04-18 15:46
Still happening, but now my workaround is not working. I'll have to revert to the previous version.

The device that crashed was a Nexus 5X.

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.isEmpty()' on a null object reference
       at com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner(CountryListSpinner.java)
       at com.firebase.ui.auth.ui.phone.CountryListSpinner.init(CountryListSpinner.java)
       at com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner(CheckPhoneNumberFragment.java)
       at com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.onViewCreated(CheckPhoneNumberFragment.java)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by samtstern** [comment] 2020-04-27 13:11
@wakim would you mind opening a new issue about this?  Also are you able to reproduce it at all?

**Comment by Mahmudul531** [comment] 2021-07-26 06:00
`Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.isEmpty()' on a null object reference
       at com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner(CountryListSpinner.java)
       at com.firebase.ui.auth.ui.phone.CountryListSpinner.init(CountryListSpinner.java)
       at com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner(CheckPhoneNumberFragment.java)
       at com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.onViewCreated(CheckPhoneNumberFragment.java)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

`  implementation 'com.firebaseui:firebase-ui-auth:7.2.0'` Causing the same issue please resolve.  Device Nexus 5X
