### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Unique transitionNames are required for all sharedElements

### ISSUE THREAD

**Issue by Shajeel-Afzal** [firebase/FirebaseUI-Android#1143] opened 2018-02-08 14:14 UTC
I am continuously getting IllegalArgumentException while trying to do login using the FirebaseUI Auth Library.

Following is the complete exception that I am getting.

```
Fatal Exception: java.lang.IllegalArgumentException: Unique transitionNames are required for all sharedElements
       at android.support.v4.app.BackStackRecord.addSharedElement(BackStackRecord.java:511)
       at com.firebase.ui.auth.ui.email.EmailActivity.onNewUser(EmailActivity.java:126)
       at com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess(CheckEmailFragment.java:206)
       at com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess(CheckEmailFragment.java:202)
       at com.google.android.gms.tasks.zzj.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### Step 2: Describe your environment

  * Android device: Samsung Grand 2
  * Android OS version: 4.4
  * Google Play Services version: 11.6.2
  * Firebase/Play Services SDK version: 11.6.2
  * FirebaseUI version: 3.1.2
  
#### Steps to reproduce:

  1. Go to Login Screen
  2. Tap on any option (Email, Facebook, Phone)
  3. The app shows the above exception.
  
#### Relevant Code:

  ```
List<AuthUI.IdpConfig> loginOptionsArray = new ArrayList<>();
loginOptionsArray.add(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build());
loginOptionsArray.add(new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build());
            loginOptionsArray.add(new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build());
            loginOptionsArray.add(new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build());

startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAllowNewEmailAccounts(true)
                        .setIsSmartLockEnabled(!BuildConfig.DEBUG)
                        .setAvailableProviders(
                                loginOptionsArray)
                        .build(),
                RC_SIGN_IN);
  ```

**Comment by samtstern** [comment] 2018-02-08 16:03
This is a duplicate of #1036, that issue was fixed in version `3.1.3` (you're using `3.1.2`)

**Closed by samtstern** 2018-02-08 16:03 UTC
