### ISSUE TITLE
!High chance: Exception java.lang.NullPointerException: Activity must not be null

### ISSUE THREAD

**Issue by tactoth** [firebase/FirebaseUI-Android#915] opened 2017-09-19 18:35 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Lenovo K33b36, Redmi Note 4, HTC U Play, LG-K120, Moto G Play
  * Android OS version: 22 - 24
  * Google Play Services version: N/A
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.3.0
  
### Step 3: Describe the problem:

I wasn't able to reproduce the issue on my own device, however, I've received lots of it from Firebase Crash Reporting. From the events before the crash happens, I found that the crash happens when you try to sign in with Firebase-Auth.

#### Steps to reproduce:

  1. As I've said, it's not easily reproducible from dev devices, however, I received lots of them from Firebase Crash Reporting
  2. However, from the events, it hanppens when you launch the auth activity in firebase UI, and before the authentication is done
  
#### Observed Results:

  * Crashes
Exception java.lang.NullPointerException: Activity must not be null
com.google.android.gms.tasks.zzf.run (zzf.java)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:914)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:707)
  
#### Expected Results:

  * Don't crash
  
#### Relevant Code:

```java
private boolean proceedWithSecureVaultBackupSetup() {
    LockDirSyncManager lockDirSyncManager = LockDirSyncManager.with(this);
    if (!lockDirSyncManager.isLoggedIn()) {
      startActivityForResult(AuthUI.getInstance().createSignInIntentBuilder()
          .setAvailableProviders(
              Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                  new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                  new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build()))
          .setIsSmartLockEnabled(!BuildConfig.DEBUG, true)
          .setTheme(getOverrideThemeResId())
          .setLogo(R.drawable.lock)
          .build(), REQUEST_CODE_SECURE_VAULT_AUTH);
      return true;
    } else if (!lockDirSyncManager.isSubscribedToBackupService()) {
      FotosIABManager.with(this).getBackUpService().buy(this, "backup_click");
      return true;
    } else {
      // already setup, so return false
      return false;
    }
  }
```

**Comment by SUPERCILEX** [comment] 2017-09-19 19:00
Can you show a stack trace with FirebaseUI code? We're probably getting a null activity from a fragment somewhere.

**Comment by tactoth** [comment] 2017-09-19 19:07
It seems to be an issue within the firebase-auth, there's no callstack involves firebase-auth-ui.

This is one of the event streams I've taken from one crash instance:


10:04:18.452 PM | gmp_nav20_crash | Fatal
-- | -- | --
arrow_drop_down | 10:04:10.569 PM | gmp_nav20_analytics | upgrade_for_free
 
arrow_drop_down | 10:04:10.453 PM | gmp_nav20_analytics | show_invite_dialog
 
arrow_drop_down | 10:03:55.150 PM | gmp_nav20_analytics | secure_vault_fake_password
 
arrow_drop_down | 10:03:46.606 PM | gmp_nav20_analytics | places_switch
Parametersswitch_value: 0firebase_screen_class: SettingsActivity
arrow_drop_down | 10:03:39.762 PM | gmp_nav20_analytics | screen_view
Parametersfirebase_screen_class: SettingsActivity
arrow_drop_down | 10:03:39.587 PM | gmp_nav20_analytics | activity_start
Parametersactivity: SettingsActivity
arrow_drop_down | 10:03:32.919 PM | gmp_nav20_analytics | screen_view
**Parametersfirebase_screen_class: AuthMethodPickerActivity**
arrow_drop_down | 10:03:20.890 PM | gmp_nav20_analytics | mopub_ad_loaded
 
arrow_drop_down | 10:03:19.278 PM | gmp_nav20_analytics | mopub_ad_loaded
 
arrow_drop_down | 10:03:08.355 PM | gmp_nav20_analytics | screen_view
**Parametersfirebase_screen_class: FacebookActivity**
arrow_drop_down | 10:03:00.741 PM | gmp_nav20_analytics | activity_stop_v2
Parametersduration: 900-1000 MILLISECONDSactivity: SettingsActivityfirebase_screen_class: AuthMethodPickerActivity
arrow_drop_down | 10:03:00.576 PM | gmp_nav20_analytics | screen_view
**Parametersfirebase_screen_class: AuthMethodPickerActivity**
arrow_drop_down | 10:02:59.769 PM | gmp_nav20_analytics | screen_view
**Parametersfirebase_screen_class: KickoffActivity**
arrow_drop_down | 10:02:59.617 PM | gmp_nav20_analytics | activity_start
Parametersactivity: SettingsActivity
arrow_drop_down | 10:02:59.615 PM | gmp_nav20_analytics | screen_view
Parametersfirebase_screen_class: SettingsActivity
  | 10:02:59.536 PM | gmp_nav20_analytics | secure_vault_backup_ok

**Comment by tactoth** [comment] 2017-09-19 19:08
It seems to be the crash is specifically about using Facebook Login

**Comment by aviadmini** [comment] 2017-09-28 10:00
Got similar issue with GMS and FUI:

`java.lang.NullPointerException: Activity must not be null
                                                                             at com.google.android.gms.common.internal.zzbo.zzb(Unknown Source)
                                                                             at com.google.android.gms.internal.zzbdr.<init>(Unknown Source)
                                                                             at com.google.android.gms.common.api.GoogleApiClient$Builder.enableAutoManage(Unknown Source)
                                                                             at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:219)
                                                                             at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:88)
                                                                             at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:76)
                                                                             at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete(CredentialSignInHandler.java:67)
                                                                             at com.google.android.gms.tasks.zzf.run(Unknown Source)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by SUPERCILEX** [comment] 2017-10-05 23:07
@samtstern I think this is a duplicate of #856 which I'm working to fix.

**Comment by samtstern** [comment] 2017-10-09 02:45
Marking as duplicate of #856

**Closed by samtstern** 2017-10-09 02:45 UTC
