### ISSUE TITLE
Error when load Facebook login

### ISSUE THREAD

**Issue by jefferson** [firebase/FirebaseUI-Android#126] opened 2016-05-20 05:47 UTC
Hi! I am using this library for the first time and I try to migrate some projects also.
I am trying make authentication with Facebook and email, email works fine but when I try Facebook the window only show "Loading..."

`5-20 02:40:45.759 13896-13925/io.atoom E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/io.atoom-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-20 02:40:45.759 13896-13896/io.atoom D/FirebaseApp: Initialized class com.google.firebase.auth.FirebaseAuth.
05-20 02:40:45.759 13896-13925/io.atoom V/GoogleSignatureVerifier: com.google.android.gms signature not valid.  Found: XXXXXXXXXXXXXX
05-20 02:40:45.769 13896-13896/io.atoom D/FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
05-20 02:40:45.769 13896-13925/io.atoom E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/io.atoom-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

And thanks for this!

**Comment by iainmcgin** [comment] 2016-05-20 23:12
I think this is a duplicate of #121 - the loading dialog is not being dismissed when authentication with an identity provider fails:

https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/idp/AuthMethodPickerActivity.java#L226

You can log the failure details / set a breakpoint at the above line of code to see what exactly has happened. We've got a fix coming for failing to dismiss the loading dialog (being tracked in #124), and we are adding additional logging throughout the failure cases to help with future diagnosis. Sorry for the inconvenience!

**Closed** 2016-05-20 23:12 UTC
Labels: duplicate
