### ISSUE TITLE
No ability to use FirebaseUI to link existing accounts

### ISSUE THREAD

**Issue by bagintz** [firebase/FirebaseUI-Android#894] opened 2017-09-06 18:04 UTC
It appears there is no way to actually initiate the FirebaseUI screens with the explicit purpose of linking to other accounts, particularly Phone Number. 

Am I missing something?

**Comment by SUPERCILEX** [comment] 2017-09-06 20:24
@bagintz Ha! One of these days I need to either blackmail some iOS developer into implementing this feature or learn Swift and do it myself. 😆 

Ok, let me back up a little and give you some context. This feature is [fully implemented](https://github.com/firebase/FirebaseUI-Android/pull/309) on the Android side of things and there's a ton of discussion [here](https://github.com/firebase/FirebaseUI-Android/issues/123), but no one has done much on the iOS side yet and Firebase wants to keep compatablity between the two features so the Android PR isn't going to get merged anytime soon. You can find some install instructions [here](https://github.com/firebase/FirebaseUI-Android/issues/123#issuecomment-316268664) and links to the documentation [here](https://github.com/firebase/FirebaseUI-Android/issues/123#issuecomment-317343123).

@samtstern This issue can be closed as a duplicate of #123.

**Comment by samtstern** [comment] 2017-09-07 00:09
Yep :-/ thanks @SUPERCILEX

**Closed by samtstern** 2017-09-07 00:09 UTC

**Comment by i3130002** [comment] 2017-11-25 19:32
Dear @SUPERCILEX  Can I ask if the issue is resolved ? I have problem linking accounts.

**Comment by danijorda1** [comment] 2022-01-04 11:24
Hi @samtstern  seems this issue has been resolved perfectly great by @SUPERCILEX  and still not avialble officially. Wouldn't it make sense to made the improvement avialble ? Even if IOS version is not alligned with this feature it doesn't make sense to hold the feature any longer for android users, specially since this has been avialble since 2017 or even before. Having the feature avialable will also encourage IOS team to deliver the feature sooner.... otherwise we will be waiting and waiting for an already avialble feature that is super helpful and mostly needed. Thanks in advance @samtstern  , and also thanks a lot @SUPERCILEX  for developing this super useful feature!
