### ISSUE TITLE
UI Flashes when singning in with one provider (phone number)

### ISSUE THREAD

**Issue by Netstep** [firebase/FirebaseUI-Android#948] opened 2017-10-06 08:04 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

### Step 1: Are you in the right place?
yes
### Step 2: Describe your environment

  * Android device: Samsung Galaxy A5 2016
  * Android OS version: 7.0
  * Google Play Services version: unknown/latest
  * Firebase/Play Services SDK version: 11.4.2/26
  * FirebaseUI version: 3.0.0
  
### Step 3: Describe the problem:
When calling Sign in UI with one provider, a quick "flashing" activity appears before sign in activity open,
according the animated demo at Auth description page, it might be provider selection activity, but not sure.

#### Steps to reproduce:

  1. Run sign in code with one provider (phone number)
  
#### Observed Results:
1. Some unwanted activity flashes on screen (quick open and close probably)
2. Phone number sign in activity opens

#### Expected Results:
Only Phone number sign in activity opens without "flashing"
  
#### Relevant Code:

startActivityForResult(
    AuthUI.getInstance()
        .createSignInIntentBuilder()
        .setAvailableProviders(
                Arrays.asList(
                              new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()
        .build(),
    RC_SIGN_IN);

**Comment by SUPERCILEX** [comment] 2018-02-24 03:58
I can't reproduce, can you try with the latest version of FirebaseUI (`3.2.1`)?

**Comment by samtstern** [comment] 2018-02-26 16:45
Looks like `KickoffActivity` has been transparent since `1.1.0` - https://github.com/firebase/FirebaseUI-Android/pull/495

So I can't really imagine where this comes from.

**Comment by samtstern** [comment] 2018-03-23 04:25
@SUPERCILEX do you think this is closeable by #1189?

**Comment by SUPERCILEX** [comment] 2018-03-23 04:42
Yes? Neither of us has been able to reproduce it so I guess close it for now and if devs bring it up, we can figure stuff out from there... SGTY? (Sound good to you?)

**Comment by samtstern** [comment] 2018-03-23 04:44
@Netstep since we have not been able to reproduce and we just recently kicked off a huge re-write of a lot of the relevant code, I am going to close this as "Not Producible" for now.  But if we see this again we will certainly re-open.

**Closed by samtstern** 2018-03-23 04:44 UTC
Labels: auth, enhancement
