### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by felipekelemen** [firebase/FirebaseUI-Android#141] opened 2016-05-25 01:00 UTC
I have gotten this error when using the new FirebaseUI with Facebook login:

```
java.lang.IllegalArgumentException: credential identifier cannot be empty
at com.firebase.ui.auth.ui.account_link.SaveCredentialsActivity.onConnected(SaveCredentialsActivity.java:120)
```

After inserting credentials and successfully logging in the app crashes and this is the error.

Do you know what might be going wrong?

**Comment by samtstern** [comment] 2016-05-25 15:13
@iainmcgin this looks to be an issue when building a credential for SmartLock (https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/account_link/SaveCredentialsActivity.java#L97).

Is it possible that the Facebook API returns non-null but still empty values for email in some cases?

**Comment by iainmcgin** [comment] 2016-05-25 18:10
It's certainly possible for Facebook accounts created with a phone number and no email address, where the Graph API would not return anything usable for the identifier. I'll take a look.

**Comment by tikurahul** [comment] 2016-05-27 22:29
`E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.rana.sahaj.myyu-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.rana.sahaj.myyu-2, /vendor/lib, /system/lib]]` is a result of a bug in Play Services where this message is accidentally logged as an `error` (instead of being a `debug`). This will be fixed in the next release.

**Comment by stba42** [comment] 2016-05-28 12:44
The same problem occured when I used the Google Login. See my pull request for an easy fix.

**Comment by aayaffe** [comment] 2016-07-02 15:38
Same here when using Google authentication

**Comment by strotz** [comment] 2016-07-30 06:40
it is probably same issue:

java.lang.IllegalArgumentException: credential identifier cannot be empty
                                                                       at com.google.android.gms.common.internal.zzab.zzh(Unknown Source)
                                                                       at com.google.android.gms.auth.api.credentials.Credential.<init>(Unknown Source)
                                                                       at com.google.android.gms.auth.api.credentials.Credential$Builder.build(Unknown Source)
                                                                       at com.firebase.ui.auth.ui.account_link.SaveCredentialsActivity.onConnected(SaveCredentialsActivity.java:122)
                                                                       at com.google.android.gms.common.internal.zzl.zzo(Unknown Source)
                                                                       at com.google.android.gms.internal.zzqd.zzm(Unknown Source)
                                                                       at com.google.android.gms.internal.zzqb.zzapm(Unknown Source)
                                                                       at com.google.android.gms.internal.zzqb.onConnected(Unknown Source)
                                                                       at com.google.android.gms.internal.zzqf.onConnected(Unknown Source)
                                                                       at com.google.android.gms.internal.zzpu.onConnected(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzd$zzj.zzarz(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzd$zza.zzx(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzd$zze.zzasb(Unknown Source)
                                                                       at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by xsorifc28** [comment] 2016-10-16 17:49
I am getting this error during release builds but not debug. Any suggestions?

**Comment by SUPERCILEX** [comment] 2016-10-17 18:18
This could also be a duplicate of #352.

**Comment by xsorifc28** [comment] 2016-10-17 19:58
I have granted access to the email, but the issue still seems to be there.

**Closed** 2016-11-04 23:00 UTC
Labels: bug, feature:auth, fix-implemented
