### ISSUE TITLE
Anonymous to existing user triggers a "FirebaseUiException: No supported providers."

### ISSUE THREAD

**Issue by niqo01** [firebase/FirebaseUI-Android#1702] opened 2019-10-28 22:22 UTC
### Environment

  * Android device: Pixel 2 XL
  * Android OS version: 10
  * Google Play Services version: Phone 19.5.30
  * Firebase/Play Services SDK version: com.google.firebase:firebase-auth:19.1.0
  * FirebaseUI version: 6.0.2
  
### Describe the problem
When trying to sign in using an existing account from an anonymous user, I am getting the following exception:
```
com.firebase.ui.auth.FirebaseUiException: No supported providers.
        at com.firebase.ui.auth.viewmodel.idp.SocialProviderResponseHandler$1$2.onSuccess(SocialProviderResponseHandler.java:95)
        at com.firebase.ui.auth.viewmodel.idp.SocialProviderResponseHandler$1$2.onSuccess(SocialProviderResponseHandler.java:88)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
```

#### Steps to reproduce:

  1. Sign in with anonymous provider 
  2. Sign up with a new account (In my case using a Google account)
  3. Sign out from the non anonymous account
  4. Sign in with anonymous provider
  5. Sign in with the existing Google account created in step 2
  
#### Observed Results:

  * Step 5 above will fail with "FirebaseUiException: No supported providers."
  
#### Relevant Code:

The code of the project I am working on is open source and available here: https://github.com/niqo01/social-cats-playground/tree/nm/firebaseAuthAnonymousIssue
I created a branch to freeze the code with the issue `nm/firebaseAuthAnonymousIssue`

AuthUI  intent code: 
```
    fun createSignInIntent(): Intent {
        return authUI.createSignInIntentBuilder()
            .enableAnonymousUsersAutoUpgrade()
            .setAvailableProviders(PROVIDERS)
            .build()
    }
```
https://github.com/niqo01/social-cats-playground/blob/nm/firebaseAuthAnonymousIssue/auth/ui/src/androidMain/kotlin/AndroidAuthUi.kt#L39

List of supported providers: 
```
val PROVIDERS = listOf(IdpConfig.PhoneBuilder().build(), IdpConfig.GoogleBuilder().build())
```
https://github.com/niqo01/social-cats-playground/blob/nm/firebaseAuthAnonymousIssue/auth/ui/src/androidMain/kotlin/AndroidAuthUi.kt#L10

Firebase auth configuration:
![firebase_auth](https://user-images.githubusercontent.com/1121251/67722067-6fa46980-f995-11e9-8bf8-2755c75efd93.png)

#### Additional notes
While debugging, I was able to see that the call to `auth.fetchSignInMethodsForEmail(email)` from the auth ui library was called with the proper email. However the number of signInMethods return is 0.
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/data/ProviderUtils.java#L195

**Comment by niqo01** [comment] 2019-10-29 02:11
It looks like it works if use an existing phone based account. I haven't tried with other provider like Facebook.

**Comment by rinav** [comment] 2020-07-07 11:41
We are facing similar issue with Google, Facebook as providers, but OTP login works properly. Do we have any workaround?

**Comment by rinav** [comment] 2020-07-12 13:59
Can someone help us with a solution?

**Comment by kalpeshat20** [comment] 2020-07-17 20:19
when this issue will be fixed

**Comment by samtstern** [comment] 2020-07-20 11:15
I am not able to reproduce this using the sample app in this repo (see `app`).  Here's what I did:

1. Open the Auth UI Demo activity
2. Sign in with Google
3. Sign out
4. Open the FirebaseUI Anonymous Account Linking activity
5. Sign in as anonymous
6. Launch Auth UI
7. Sign in with Google
8. Address merge conflicts

Then I was properly signed in as my gmail account.

**Comment by samtstern** [comment] 2020-11-02 11:59
Ok since I was not able to reproduce this and nobody else has offered alternative instructions I am going to close this issue.  If anyone can reliably reproduce this in the future please just add a comment telling me how and I will re-open it!

**Closed by samtstern** 2020-11-02 11:59 UTC
Labels: auth, type: bug
