### ISSUE TITLE
Add support for ordering/transforming data from Firebase Database before displaying it

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-Android#389] opened 2016-11-04 17:18 UTC
One of our most requested database features is being able to sort/order/transform stuff from database before displaying it in a view. Mirrors https://github.com/firebase/FirebaseUI-iOS/issues/183

**Comment by SUPERCILEX** [comment] 2016-11-04 19:00
Possible duplicate of #15.

**Comment by samtstern** [comment] 2017-01-31 19:28
Cleaning old issues and this is a duplicate of #15.

**Closed by samtstern** 2017-01-31 19:28 UTC
Labels: feature:database
