### ISSUE TITLE
FirebaseUiLogin

### ISSUE THREAD

**Issue by martmwangi** [firebase/FirebaseUI-Android#87] opened 2016-03-01 13:14 UTC
Hi, I have followed all the steps and yet I keep getting a runtime error, a nullPointerException error. [Here](https://github.com/martmwangi/Logintest/blob/master/app/src/main/java/com/example/hulk/logintest/MainActivity.java)
Where I have the onStart method. What am I missing?

**Comment by puf** [comment] 2016-03-01 13:57
If you implement the `getFirebaseReference()` method, that NPE will
disappear:


@Override
protected Firebase getFirebaseRef() {
return null;
}

**Comment by puf** [comment] 2016-03-01 13:58
Duplicate of https://github.com/firebase/FirebaseUI-Android/issues/85

**Closed by puf** 2016-03-01 13:58 UTC

**Comment by martmwangi** [comment] 2016-03-01 18:06
Actually, I have and still am getting the same

**Comment by puf** [comment] 2016-03-01 19:31
The project you linked returns `null` from `getFirebaseReference()`. That
will raise an NPE. If your code doesn't do that, what is the linked code
for?

I'll need to either see the actual code or the full stack trace (and
preferably both) to be able to help here.
