### ISSUE TITLE
FirebaseUI Pagination

### ISSUE THREAD

**Issue by DionMeliala** [firebase/FirebaseUI-Android#1058] opened 2017-12-16 09:50 UTC
Hello, I need Help for Firebase UI Pagination. can u help me with that ?
Thank you.

**Comment by SUPERCILEX** [comment] 2017-12-16 18:37
@DionMeliala It isn't supported yet, but we're thinking about it.

Duplicate of https://github.com/firebase/FirebaseUI-Android/issues/17.

**Closed** 2017-12-18 17:28 UTC
