### ISSUE TITLE
Hashcode is not a stable id for FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by hvisser** [firebase/FirebaseUI-Android#590] opened 2017-02-14 10:05 UTC
`FirebaseRecyclerAdapter` is using `hashcode()` for [it's item id's](https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java#L176). The `hashcode()` of a key isn't a stable or unique id as required by `RecyclerView`. Multiple keys may produce the same `hashcode()`. As per `RecyclerView` docs:

> Return the stable ID for the item at position. If hasStableIds() would return false this method should return NO_ID. The default implementation of this method returns NO_ID.

The easiest fix is to remove the implementation, since `setHasStableIds()` isn't being called in the adapter. Stable ids help with RecyclerView animations though, so another approach is to fake an id by keeping a map of keys with their generated id's to ensure the stability of the ids when data is updated.

**Comment by SUPERCILEX** [comment] 2017-03-14 05:53
@samtstern This issue can be marked as `fix-implemented` since we are no longer overriding `getItemId` in the `v2.0.0` FirebaseUI Database.

**Comment by rahul-991** [comment] 2017-03-14 18:49
@SUPERCILEX So does removing the getItemId() overriden function ensure every item has a unique item ID? I was having issues with multiple IDs for recycler view items.

**Comment by SUPERCILEX** [comment] 2017-03-14 19:45
@rahul-991 Are you setting `setHasStableIds(true)`? Otherwise, this shouldn't matter because the default implementation returns `NO_ID = -1`.

**Comment by rahul-991** [comment] 2017-03-14 19:48
@SUPERCILEX I'm sorry I do not know where to set this, could you please point out where I need to put this command so that every item in a firebase recycler view has its own unique ID? Thanks!

**Comment by SUPERCILEX** [comment] 2017-03-14 20:01
@rahul-991 This issue shouldn't really matter to you or 99% of people using the `FirebaseRecyclerAdapter`.
 (`setHasStableIds` allows the recyclerview to optimize item update performance.)

**Comment by rahul-991** [comment] 2017-03-14 20:10
@SUPERCILEX I am actually facing an issue which **I THINK** may be because the items do not have unique IDs. I have a chat application and I am implementing a feature of long press on a recyclerview item, which would then highlight the item. 
So in my base activity, I record the long press by caching the positions in a Set, which is then passed to and used by the FirebaseRecyclerAdapter (in the onBindView method) to change the color of the background of the recyclerview item layout. But when I do select one item, and scroll down the list, various random position items get highlighted as well, even though on checking the set contents on the console show the positions of the selected items. 
I do not know where I am going wrong, and have tried using the getItemID() method to store hash values in the set, but I am unable to resolve that issue. Is this issue related to what I am facing?

**Comment by hvisser** [comment] 2017-03-14 20:52
Yes, RV will do some animations automatically with stable ids set, so in that sense removing `getItemId()` is a regression. For proper animation support you want to have some kind of id set on the adapter.

**Comment by SUPERCILEX** [comment] 2017-03-14 21:17
@hvisser This isn't a regression because we weren't setting `setHasStableIds(true)` and as you mentioned that would have been incorrect.

@rahul-991 Funny that you mention that because I built the same feature and encountered the same issue. The recyclerview recycles views (duh! 😄) so you can't rely on outside changes, your view holders have to manage their own state. Here's how I built it: I keep track of model classes that have been selected and in `onBindViewHolder` I check if the data is inside my list of selected items:
```java
teamHolder.bind(/* ... */, mMenuManager.getSelectedTeams().contains(team));
```
Then inside the view holder I update the status of the item:
```java
private void updateItemStatus() {
    itemView.setBackground(getRippleDrawable());
    if (mIsItemSelected) {
        Glide.with(itemView.getContext()) // This fixes a weird bug where Glide overwrites your image after `onResume`
                .load("")
                .placeholder(ContextCompat.getDrawable(itemView.getContext(),
                                                       R.drawable.ic_check_circle_grey_144dp))
                .into(mLogo);
        itemView.setBackgroundColor(Color.parseColor("#462a56c6")); // Tinted blue
    } else {
        setTeamLogo();
    }
}
```

**Closed** 2017-06-12 16:55 UTC
Labels: bug, feature:database, fix-implemented
