### ISSUE TITLE
Token does not refresh if phone date is set to future then moved back

### ISSUE THREAD

**Issue by hamzahrmalik** [firebase/FirebaseUI-Android#855] opened 2017-08-07 18:43 UTC
If a phone date is moved to the future, then moved back, the token never refreshes again (I'm talking about the login token which is sent to server to verify the user account)

It is simple to reproduce. Simply using 

        final FirebaseAuth auth = FirebaseAuth.getInstance();
        if (auth.getCurrentUser() != null)
            auth.getCurrentUser().getIdToken(true)
                    .addOnCompleteListener(new OnCompleteListener<GetTokenResult>() {
                        public void onComplete(@NonNull Task<GetTokenResult> task) {
                            if (task.isSuccessful()) {
                                final String idToken = task.getResult().getToken();
                                Util.log(auth.getCurrentUser().getUid());
                                Util.log("ID TOKEN " + idToken);
                                

                            }
                        }
                    });

The idToken value usually changes every hour. However, if the phone date is moved to future, say a week from now, then back again, the token never refreshes again. Even if I uninstall or signout or reboot or delete account from Firebase Console or any combination of the above. i assume itll refresh a week and an hour from now, but cannot be sure until then

Even if i sign in with a different account, i get the exact same token, which the server says expired a few hours ago. It is never refreshing this token.

I assume it is because it thinks there is a week left until it expires. How can we work around this problem or fix it?

**Comment by samtstern** [comment] 2017-08-07 23:55
@hamzahrmalik that's interesting, thanks for reporting this.  Can I ask why a user might set his/her clock to the future?

**Comment by hamzahrmalik** [comment] 2017-08-07 23:59
@samstern I did it while testing another feature of the app to check if it works (the other feature was time based)

But I suppose anyone could do it by accident and more importantly I seem to have lost a test device

**Comment by samtstern** [comment] 2017-08-08 00:32
@hamzahrmalik in the meantime, you can clear data on your test app to clear the token.  That should fix your test device.

**Comment by hamzahrmalik** [comment] 2017-08-08 00:34
Right except uninstalling the app did not fix it. It's quite late here but in the morning I'll try again, it might have refreshed by then 

But before, even using different logins didn't work

**Comment by samtstern** [comment] 2017-08-08 04:13
As a last resort you can try running "adb shell pm clear
com.google.android.gms" to clear data on Google Play services.  Only do
this on a test device, as if you do it on a real device you'll likely lose
some important settings.

**Comment by hamzahrmalik** [comment] 2017-08-08 08:26
Thanks but how would I fix it for a production device. Is there a way to force a refresh or something?

**Comment by samtstern** [comment] 2017-08-08 15:21
Can you try using the `FirebaseUser#getIdToken()` method and passing `true` for the `forceRefresh` argument?

https://developers.google.com/android/reference/com/google/firebase/auth/FirebaseUser.html#getIdToken(boolean)

**Comment by hamzahrmalik** [comment] 2017-08-08 15:22
@samstern Thats what im using, see my original post, it has some code

**Comment by samtstern** [comment] 2017-08-08 15:27
@hamzahrmalik whoops you're right.  There is no other way I know of to force a refresh. I am still asking around for better answers.

**Comment by hamzahrmalik** [comment] 2017-08-08 15:28
@samtstern  thanks appreciate that, also by the way, its still not working i tried again

**Comment by hamzahrmalik** [comment] 2017-08-09 21:40
@samtstern 

Just an update, it is still giving me the same token now, which expired about 51 hours ago now

**Comment by anasnisar** [comment] 2017-08-10 17:29
if (task.isSuccessful()) {
                    progressDialog.dismiss();

                    String current_userid = firebaseAuth.getCurrentUser().getUid();

                    String TokenID = FirebaseInstanceId.getInstance().getToken();

                    userdatabase.child(current_userid).child("device_token").setValue(TokenID).addOnSuccessListener(new OnSuccessListener<Void>() {
                        @Override
                        public void onSuccess(Void aVoid) {

                            Intent intent = new Intent(LoginActivity.this, MainActivity.class);
                            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                            startActivity(intent);
                            finish();

                        }
                    });

                }
Use this way to get Token_id i hope this will work.

**Comment by hamzahrmalik** [comment] 2017-08-10 19:04
@anasnisar it seems like youre getting the TokenID then saving it into the database. However, the TokenID retrieved by that method isnt valid

InvalidArgumentException: The JWT string must have two dots

for the string

ek8onlTZyc4:APA91bH_rVT0JHF8IvF0BKb_nb7FrK-u35dQ1s5L-B_wemiXYdgZEUueUrasKb1s_e6-uhclLlojalEn8ticWB-qPsXJUiLQYEYF2kFNJujKmKyCLz-Yu2nHy40Sb-DCwge74Nwh-gdM

Retrieved from

    FirebaseInstanceId.getInstance().getToken();

**Comment by anasnisar** [comment] 2017-08-11 05:22
oh sorry I forgot to tell you that you have to make a child in the firebase in which you can create your yours then save token id using my method this works great for me

**Comment by hamzahrmalik** [comment] 2017-08-11 09:59
@anasnisar im pretty sure that method is for getting the FCM token. My issue is with the login token

**Comment by hamzahrmalik** [comment] 2017-09-09 20:33
Update:

I still get the same issue on that one device which was moved forward a year. I still get given a token which expired on 2017-08-07T17:39:12+00:00

**Comment by dennywahyu** [comment] 2017-10-04 04:36
@hamzahrmalik have you found any solution for this issue?

**Comment by hamzahrmalik** [comment] 2017-10-04 08:26
@dennywahyu I filed a bug with Firebase. This is their response 


-The client side can't trust the backend's clock, since the two may be mismatched
- There's no version of a canonical clock on the client-side; changing the system clock changes everything about how the system views time
- Once the token is received, it's stamped with the current time on the client side; changing the clock doesn't change the timestamp
- The only means to detect these changes is via the ACTION_TIME_CHANGED intent (https://developer.android.com/reference/android/content/Intent.html#ACTION_TIME_CHANGED); while the client could listen for these calls, it wouldn't be worth the effort (or SDK size cost) in most cases.

**Comment by dennywahyu** [comment] 2017-10-04 08:41
So, that means there wont be any SDK update (or server side) to fix this issue?

But have you find any hack or workaround for this?

**Comment by Antpachon** [comment] 2017-10-05 10:03
Same issue here, I messed up with the date doing tests, now I am getting expired token, even uninstalling the app it doesn't fix the problem..

**Comment by hamzahrmalik** [comment] 2017-10-05 11:55
Yep it appears it can't be fixed. As I posted above, they aren't willing to fix it. Surely FORCE refresh should just force it. But apparently not

**Comment by hamzahrmalik** [comment] 2017-10-05 11:55
I haven't found any workaround or anything. The only solution seems to be clearing data for Google play services

**Comment by isaisachen** [comment] 2017-10-05 16:38
I think folks in this thread are seeing a few different issues. To clarify:
1. The JWT's  “iat” (token issue time) and “exp” (token issue time + token expiresIn) is server clock. If your test is comparing those values, make sure to have right clock in your test.
2. There's indeed local token cache in Firebase Auth SDK which is using device local clock. The assumption is, user is less likely to change their local clock now and then; but there's larger chance user's clock doesn't align with servers'. So for developers above setting clock forward and then back, you should not be seeing any issue with token cache. But again, if you want to check JWT's iat / exp, make sure to use the right clock
3. Clearing your app's cache or uninstall / reinstall should fix your problem.

If you are still seeing issues, please uninstall and start from clean and report:
1. Local clock when you make the 1st getToken call and the JWT you get back
2. What you do to the clock
3. Local clock when you make the 2nd / 3rd... getToken call and the JWT you get back
...

Thanks.

**Comment by isaisachen** [comment] 2017-10-05 16:41
By reporting with your "JWT you get back", I mean the iat / exp part (and I don't mean the raw JWT which will leak your aud / sub here :))

**Comment by samtstern** [comment] 2017-10-10 18:06
Closing after explanation by @isaisachen, this is intended behavior of the Firebase Auth SDK for now and cannot be fixed by FirebaseUI.

**Closed by samtstern** 2017-10-10 18:06 UTC
