### ISSUE TITLE
Using 2 item layouts with the FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by Meeks91** [firebase/FirebaseUI-Android#108] opened 2016-04-23 16:14 UTC
With the old FirebaseListAdapter the constructor had the 'int layout,int outgoingLayout' parameters which allowed us to configure separate layouts for incoming and outgoing messages. 

There is only one layout in the FirebaseRecyclerAdapter constructor. How would I use two layouts with the FirebaseRecyclerAdapter? 

I will try and create my own but it could be useful to know if there is an out of the box solution for this. 

Thanks in advance.

**Comment by puf** [comment] 2016-04-23 16:24
FirebaseUI never had a `FirebaseListAdapter()` with that signature. Can you link to the `FirebaseListAdapter` you are referring to?

**Comment by Meeks91** [comment] 2016-04-23 16:36
Thanks for the prompt response, 

I originally built off of the AndroidChat project. 

Perhaps the structure from the [https://github.com/firebase/AndroidChat/blob/master/app/src/main/java/com/firebase/androidchat/ChatListAdapter.java](url)  class has been updates but in my project the constructor was like this: 

/**
 * @author greg
 * @since 6/21/13
 *
 * This class is an example of how to use FirebaseListAdapter. It uses the <code>Chat</code> class to encapsulate the
 * data for each individual chat message
 */
public class ChatListAdapter extends FirebaseListAdapter<Chat> {

    // The mUsername for this client. We use this to indicate which messages originated from this user
    private String mUsername;

    public ChatListAdapter(Query ref, Activity activity, int layout,int outgoingLayout, String mUsername, Context context) {
        super(ref, Chat.class, layout, outgoingLayout, activity, mUsername, context); 
   // the super class takes two layouts 
        this.mUsername = mUsername;
    }

**Comment by puf** [comment] 2016-04-23 16:54
As you noticed that class too only has a single layout. Most likely the forked version in your app added the second layout, which is application specific. We have an open [enhancement request for adding support for having different layouts per item](https://github.com/firebase/FirebaseUI-Android/issues/14), but this has not been scheduled yet.

Closing as a dupe of #14

**Closed** 2016-04-23 16:54 UTC

**Comment by Meeks91** [comment] 2016-04-23 23:55
Okay, 

I made my own version of the FirebaseRecyclerAdapter in the end to switch between the layouts. 

Cheers

**Comment by jernkuan** [comment] 2016-10-19 04:54
I was looking at this, it seems that you can just override getItemViewType from FirebaseRecyclerAdapter to switch between the type of layout?
