### ISSUE TITLE
Old Firebase profiles not merging

### ISSUE THREAD

**Issue by svangsgaard** [firebase/FirebaseUI-Android#560] opened 2017-01-31 14:41 UTC
Hello

It has come to my attention that users created *before* the option to only allow one email address per user is set won't be merged.

For example:
1. I have a user who has logged ind using Facebook. He gets userId facebook:12345678900
2. I set the option to only allow one email address per user.
3. Now new users get a different kind of userId, this is fine. These users can merge different providers. All is good for the new users.
4. Now my old user wishes to log in using his Google account (maybe he switched to Android from an iPhone). His Google account is using the same email address as his Facebook account. 
5. My old user now has two accounts in my system. 

Is this by design?
Why didn't the accounts merge like the new users? 

He could've just kept the old userId (I know the old userId have the word facebook in it, but still everything would have worked) 

Thank you in advance.

**Comment by samtstern** [comment] 2017-01-31 15:51
@svangsgaard yes this is by design but I see how it can be a confusing experience.  Because there's nothing FirebaseUI can do about this I am going to close the issue, but I will file a bug with the team and see if the opinion on this has changed.

**Closed by samtstern** 2017-01-31 15:51 UTC
