### ISSUE TITLE
Facebook login crashes app

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [firebase/FirebaseUI-Android#51] opened 2016-01-04 21:02 UTC
Hi ! i'm trying to login on my app using facebook. When I authorize my app on facebook's app, my app pops up again but it crashes with this log:
```
01-04 15:59:29.423 6870-6870/com.example.rafa93br.firebase E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.rafa93br.firebase, PID: 6870

java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.FragmentTransaction android.app.FragmentManager.beginTransaction()' on a null object reference
at android.app.DialogFragment.dismissInternal(DialogFragment.java:287)
at android.app.DialogFragment.dismiss(DialogFragment.java:258)
at com.firebase.ui.auth.core.FirebaseLoginDialog$1.onSuccess(FirebaseLoginDialog.java:130)
at com.firebase.ui.auth.core.FirebaseAuthProvider$1.onAuthenticated(FirebaseAuthProvider.java:33)
at com.firebase.client.authentication.AuthenticationManager$AuthAttempt$2.run(AuthenticationManager.java:90)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
01-04 16:00:33.083 6870-6870/com.example.rafa93br.firebase I/Process: Sending signal. PID: 6870 SIG: 9
```

**Comment by abehaskins** [comment] 2016-01-04 21:15
Hi! Can you please post the code for you're activity so I can reproduce this issue?

**Comment by rafaelcorreiapoli** [comment] 2016-01-04 21:30
```
package com.example.rafa93br.firebase;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;

import com.example.rafa93br.firebase.model.Shareable;
import com.facebook.appevents.AppEventsLogger;
import com.firebase.client.AuthData;
import com.firebase.client.Firebase;
import com.firebase.ui.auth.core.FirebaseLoginBaseActivity;
import com.firebase.ui.auth.core.FirebaseLoginError;
import com.firebase.ui.auth.core.SocialProvider;

public class MainActivity extends FirebaseLoginBaseActivity implements View.OnClickListener{
    Button mButtonLogin;
    Firebase myFirebaseRef;
    Button mButtonShowSignUp;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Firebase.setAndroidContext(this);
        myFirebaseRef = new Firebase("https://shact.firebaseio.com/");
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mButtonLogin = (Button) findViewById(R.id.buttonLogin);
        mButtonShowSignUp = (Button) findViewById(R.id.buttonShowSignUp);

        mButtonLogin.setOnClickListener(this);
        mButtonShowSignUp.setOnClickListener(this);
    }

    @Override
    protected void onStart() {
        super.onStart();
        // All providers are optional! Remove any you don't want.
        setEnabledAuthProvider(SocialProvider.facebook);
        setEnabledAuthProvider(SocialProvider.password);
    }

    @Override
    protected void onFirebaseLoggedIn(AuthData authData) {
        Log.i("TAG", "logged in");
    }

    @Override
    protected void onFirebaseLoggedOut() {
        Log.i("TAG", "logged out");
    }

    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {
        Log.i("TAG", "login provider error");
    }

    @Override
    protected void onFirebaseLoginUserError(FirebaseLoginError firebaseLoginError) {
        Log.i("TAG", "login error");
    }

    @Override
    protected Firebase getFirebaseRef() {
        return myFirebaseRef;
    }

    @Override
    protected void onResume() {
        super.onResume();

        // Logs 'install' and 'app activate' App Events.
        AppEventsLogger.activateApp(this);
    }

    @Override
    protected void onPause() {
        super.onPause();

        // Logs 'app deactivate' App Event.
        AppEventsLogger.deactivateApp(this);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()){
            case R.id.buttonLogin:
                    showFirebaseLoginPrompt();
                break;
            case R.id.buttonShowSignUp:
                    startActivity(new Intent(this, SignUp.class));
                break;

        }
    }
}

````

**Comment by abehaskins** [comment] 2016-01-15 17:56
I can't seem to reproduce this issue, so I'm closing for now.

**Closed by abehaskins** 2016-01-15 17:56 UTC
Labels: investigating-fix

**Comment by Isabellle** [comment] 2016-04-05 21:29
I have exactly the same issue.

`package com.example.student5303.yatoo.activity;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.example.student5303.yatoo.Constants;
import com.example.student5303.yatoo.R;
import com.example.student5303.yatoo.core.App;
import com.example.student5303.yatoo.model.User;
import com.firebase.client.Firebase;
import com.firebase.ui.auth.core.AuthProviderType;
import com.firebase.ui.auth.core.FirebaseLoginBaseActivity;
import com.firebase.ui.auth.core.FirebaseLoginError;

import java.util.ArrayList;

public class SplashScreenActivity extends FirebaseLoginBaseActivity implements View.OnClickListener {

    private App app;
    private ArrayList<User> userArrayList;
    private Button loginButton;
    private Firebase firebaseRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash_screen);

        app = App.getSharedInstance();
        firebaseRef = new Firebase(Constants.FIREBASE_URL);

        loginButton = (Button) findViewById(R.id.splash_login_button);
        loginButton.setOnClickListener(this);

    }

    @Override
    public void onClick(View v) {
        switch(v.getId()){
            case R.id.splash_login_button:
                showFirebaseLoginPrompt();
                break;
        }
    }

    @Override
    protected Firebase getFirebaseRef() {
        return null;
    }

    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    protected void onFirebaseLoginUserError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    protected void onStart() {
        super.onStart();
        setEnabledAuthProvider(AuthProviderType.FACEBOOK);
    }
}
`

**Comment by grvsingh44** [comment] 2016-04-16 11:32
It still not working:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: , PID: 8651
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{**.****..Login}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.client.Firebase$AuthStateListener com.firebase.client.Firebase.addAuthStateListener(com.firebase.client.Firebase$AuthStateListener)' on a null object reference
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.client.Firebase$AuthStateListener com.firebase.client.Firebase.addAuthStateListener(com.firebase.client.Firebase$AuthStateListener)' on a null object reference
                                                                          at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.onStart(FirebaseLoginBaseActivity.java:151)
                                                                          at com.dclaundry.customer.LoginFragment.onStart(LoginFragment.java:55)
                                                                          at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                          at android.app.Activity.performStart(Activity.java:6253)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by puf** [comment] 2016-04-16 14:58
Different issue. It looks like you forgot to implement `getFirebaseRef()`. See https://github.com/firebase/FirebaseUI-Android/issues/50
