### ISSUE TITLE
Remove field asking for First & last name in email signup

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-Android#960] opened 2017-10-10 15:09 UTC
Is it possible to not ask for the First & last name of the user when signing up through email? I would like it to only be email, password, and confirm password (if possible). Please get back to me asap. Thanks!

**Comment by SUPERCILEX** [comment] 2017-10-10 17:11
Nope, unfortunately not. See #806 and duplicate #467.

**Comment by samtstern** [comment] 2017-10-10 17:56
Closing as duplicate of #806 and #467

**Closed by samtstern** 2017-10-10 17:56 UTC

**Comment by markoars** [comment] 2020-09-13 11:33
it is possible now:
