### ISSUE TITLE
Add `IdpProvider#startLogin(Fragment)`

### ISSUE THREAD

**Issue by goncalossilva** [firebase/FirebaseUI-Android#490] opened 2017-01-04 12:00 UTC
As it stands, `IdpProvider#startLogin` expects an activity and nothing else. This is problematic when invoking it from a fragment, as the client needs to manually proxy `Activity#onActivityResult` to its own fragments' `onActivityResult` so that they can call `IdpProvider#onActivityResult`.

By using `Fragment#startActivityForResult` inside each provider, Android will take care of the proxying transparently, hence no leaking to the associated `Activity` is necessary.

**Comment by samtstern** [comment] 2017-01-04 18:24
@goncalossilva are you calling `IdpProvider#startLogin` directly from your own code?

**Comment by SUPERCILEX** [comment] 2017-01-04 19:49
@goncalossilva I don't think the `provider` package is public api (that's up to debate in #491), but if you want to know the reason behind that decision, here it is: it's all Twitter's fault as usual (sorry, I don't have high regards for Twitter's api). Their [`TwitterAuthClient#authorize`](https://docs.fabric.io/javadocs/twitter-core/2.3.0/index.html) method only supports activities. Internally, we've been using an activity and forwarding event to our Fragments like so: https://github.com/firebase/FirebaseUI-Android/blob/version-1.1.0-dev/auth/src/main/java/com/firebase/ui/auth/KickoffActivity.java#L79.

**Comment by goncalossilva** [comment] 2017-01-05 16:49
@samtstern Yes. We found the UIs and their flows on this library to be a tad too restrictive, but most of the things behind the scenes are _very_ useful. At the moment, these are the classes referenced in our codebase:
```
AuthUI
IdpResponse
provider.IdpProvider
provider.GoogleProvider
provider.FacebookProvider
util.GoogleApiConstants
```

@SUPERCILEX Huh, Twitter 😩  It's the only provider we're not using, hence I missed this when checking if there were any limitations to adding a `startLogin(Fragment)` method.

**Comment by samtstern** [comment] 2017-01-05 17:02
@goncalossilva thanks for the clarification.  As @SUPERCILEX we don't consider those classes to be part of the public API so we don't plan to add `Fragment` support there since we don't use it internally.

While I totally understand your use case, I am going to close this issue because it's working as intended from our perspective.  I think you may want to consider forking the library and modifying it to suit your needs if you find the current API surface too restrictive.  Thanks for the input!

**Closed by samtstern** 2017-01-05 17:02 UTC
