### ISSUE TITLE
Exception while doing Email/Password Login

### ISSUE THREAD

**Issue by Shajeel-Afzal** [firebase/FirebaseUI-Android#153] opened 2016-05-29 10:06 UTC
I am getting `com.firebase.ui.auth.ui.email.RegisterEmailActivity}: android.view.InflateException: Binary XML file line #91: Error inflating class Button` exception while doing email/password login using 

```
startActivityForResult(
                        // Get an instance of AuthUI based on the default app
                        AuthUI.getInstance().createSignInIntentBuilder().build(),
                        RC_SIGN_IN);
```
Am I missing any step?

complete exception is:

``` 
java.lang.RuntimeException: Unable to start activity ComponentInfo{PACKAGE_NAME/com.firebase.ui.auth.ui.email.RegisterEmailActivity}: android.view.InflateException: Binary XML file line #91: Error inflating class Button
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: android.view.InflateException: Binary XML file line #91: Error inflating class Button
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                at com.firebase.ui.auth.ui.email.RegisterEmailActivity.onCreate(RegisterEmailActivity.java:64)
                                                                                at android.app.Activity.performCreate(Activity.java:5231)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: android.content.res.Resources$NotFoundException: File res/drawable/rounded_button.xml from drawable resource ID #0x7f0200a1
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:2096)
                                                                                at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                                at android.view.View.<init>(View.java:3554)
                                                                                at android.widget.TextView.<init>(TextView.java:623)
                                                                                at android.widget.Button.<init>(Button.java:107)
                                                                                at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
                                                                                at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
                                                                                at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
                                                                                at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at com.firebase.ui.auth.ui.email.RegisterEmailActivity.onCreate(RegisterEmailActivity.java:64) 
                                                                                at android.app.Activity.performCreate(Activity.java:5231) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                                at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
                                                                                at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:186)
                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
                                                                                at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:2092)
                                                                                at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                                at android.view.View.<init>(View.java:3554) 
                                                                                at android.widget.TextView.<init>(TextView.java:623) 
                                                                                at android.widget.Button.<init>(Button.java:107) 
                                                                                at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62) 
                                                                                at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58) 
                                                                                at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039) 
                                                                                at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at com.firebase.ui.auth.ui.email.RegisterEmailActivity.onCreate(RegisterEmailActivity.java:64) 
                                                                                at android.app.Activity.performCreate(Activity.java:5231) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                at dalvik.system.NativeStart.main(Native Method)

```

**Comment by samtstern** [comment] 2016-05-31 18:57
This is a duplicate of #145 , let's continue the discussion there.

**Closed** 2016-05-31 18:58 UTC
