### ISSUE TITLE
Support for multi-section tables

### ISSUE THREAD

**Issue by mcdonamp** [firebase/FirebaseUI-Android#14] opened 2015-09-29 23:40 UTC
See https://github.com/firebase/FirebaseUI-iOS/issues/8

**Comment by SUPERCILEX** [comment] 2017-04-27 20:13
@samtstern I believe this issue can be closed as a duplicate of #305. (My apologies if I am incorrect as I'm unsure what `multi-section tables` are.)

**Comment by samtstern** [comment] 2017-04-27 20:14
I think this is slightly different, it's more of an iOS thing but could still be relevant here.  It's lists that are broken up by "section headers" like you might see in a preferences screen or something.

**Comment by SUPERCILEX** [comment] 2017-04-27 20:16
@samtstern Ohhhhhh, that makes way more sense! Nevermind then, that would be cool! 😄

**Comment by TheCraftKid** [comment] 2017-07-07 20:38
This has been sitting for a while, so I'll say this: I _think_ this is beyond the scope of this library as this isn't particularly Firebase-related.

**Comment by samtstern** [comment] 2017-07-10 15:21
The related iOS issue is closed so I think @TheCraftKid is right.  I'll close this for now, there is clearly not much demand.

**Closed by samtstern** 2017-07-10 15:21 UTC
Labels: enhancement, feature:database
