### ISSUE TITLE
Firebase Auth becomes null after login and then gets authenticated again

### ISSUE THREAD

**Issue by sunny061** [firebase/FirebaseUI-Android#92] opened 2016-03-09 12:17 UTC
Hi,

I am testing the Facebook social login with Firebase. I have set an AuthStateListener in my Application class in which I noticed that sometimes after I launch my app, the auth becomes null and then gets a value again.

I check the auth on app launch and redirect if the user is logged in, however, sometimes in my logs I can see it becomes null and then gets a value again which causes my UI to redirect to Login and then back to app again after initially going through. I can't figure out whats wrong so any help would be appreciated. Thanks

Regards

**Comment by puf** [comment] 2016-03-09 14:14
An educated guess sounds like the user's session expires. But it's difficult to say anything specific, without seeing the behavior (or logs).

**Comment by abehaskins** [comment] 2016-04-01 17:38
Since it's been nearly a month without logs or other details I'll close this. Happy to reopen if we can reproduce.

**Closed by abehaskins** 2016-04-01 17:38 UTC
