### ISSUE TITLE
Silent signin doesn't work

### ISSUE THREAD

**Issue by trogalko** [firebase/FirebaseUI-Android#1553] opened 2018-12-17 01:48 UTC
### Step 2: Describe your environment

  * Android device: Samsung Galaxy Note 2
  * Android OS version: 6
  * Google Play Services version: 14.7.99
  * Firebase/Play Services SDK version: 49 , com.google.firebase:firebase-core:16.0.4
  * FirebaseUI version: 4.2.1
  
### Step 3: Describe the problem:

I Followed the example in the app folder in this repository for firebaseui-auth silent sign in,

  1. Internet connection is OK, and internet permission is added to manifest file. Furthermore, I'm able to show query from firestore db to recyclerview
  2. This is code for silent signin click, exactly the same with example code 

```java
   @OnClick(R.id.sign_in_silent)
    public void silentSignIn() {
        List<AuthUI.IdpConfig> providers = getSelectedProviders();
        AuthUI.getInstance().silentSignIn(this, providers)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            startSignedInActivity(null);
                        } else {
                            showSnackbar(R.string.sign_in_failed);
                        }
                    }
                });
    }
```

  3. This sign in click button code  with hardcoded modifications  

```java
    @OnClick(R.id.sign_in)
    public void signIn() {
        AuthUI.SignInIntentBuilder builder =  AuthUI.getInstance().createSignInIntentBuilder()
                .setTheme(getSelectedTheme())
                .setLogo(getSelectedLogo())
                .setAvailableProviders(getSelectedProviders())
                .setIsSmartLockEnabled(true);
        //.setIsSmartLockEnabled(mEnableCredentialSelector.isChecked(),
        //mEnableHintSelector.isChecked());

        if (getSelectedTosUrl() != null && getSelectedPrivacyPolicyUrl() != null) {
            builder.setTosAndPrivacyPolicyUrls(
                    getSelectedTosUrl(),
                    getSelectedPrivacyPolicyUrl());
        }

        startActivityForResult(builder.build(), RC_SIGN_IN);
    }
```
  
#### Observed Results:

  100% failed, with smart lock enabled, and I have signed in before.
  
#### Expected Results:

  The silent sign click button should signed me in

**Comment by samtstern** [comment] 2018-12-17 16:53
@trogalko silent sign in only works if we can find a way to sign you in without UI.  That means either a saved account in SmartLock (and only one option there) or a saved Google Sign In account.  Are those conditions met in your case?

**Comment by trogalko** [comment] 2018-12-26 01:49
Yes, I have enabled Smart Lock for Password, and Auto sign-in, the application also not in the Never save list app.

**Comment by samtstern** [comment] 2019-01-02 23:30
If you do a "regular" sign in (not silent) are you signed in automatically with smart lock?

**Comment by samtstern** [comment] 2019-01-18 17:07
@trogalko are you still having this issue?  If so see my last question.

**Comment by trogalko** [comment] 2019-01-20 10:37
> @trogalko are you still having this issue? If so see my last question.
I'll try to combine FirebaseUI Auth with SharedPreferences.
Btw, here is the my app. link on Play Store :
https://play.google.com/store/apps/details?id=com.rscmkencana.rscmkencanamobile&hl=en

**Comment by samtstern** [comment] 2019-01-22 16:23
@trogalko I think this is working as intended.  In a situation where you are "being prompted to choose user account to sign in without to enter password" that means we can't do silent sign in.  Silent sign in only works when there is exactly one account to choose from and the user has already granted enough permissions for the sign in to proceed without any UI.

That means either a single saved account in SmartLock (so you get the blue bar) or a single Google account where the current device/app has already been authorized.

Thanks for providing all the information, closing this bug as WAI for now.  Let me know if I've gotten it wrong!

**Closed by samtstern** 2019-01-22 16:23 UTC
Labels: needs-info
