### ISSUE TITLE
 java.lang.IllegalArgumentException: Key not found in FirebaseArray

### ISSUE THREAD

**Issue by dimipaun** [firebase/FirebaseUI-Android#1468] opened 2018-10-03 13:38 UTC
Not much to add here, I see this crash in Crashlytics logs:

  ```
Fatal Exception: java.lang.IllegalArgumentException: Key not found
       at com.firebase.ui.database.FirebaseArray.getIndexForKey(FirebaseArray.java:122)
       at com.firebase.ui.database.FirebaseArray.onChildAdded(FirebaseArray.java:69)
       at com.google.firebase.database.obfuscated.zzr.zza(com.google.firebase:firebase-database@@16.0.2:79)
       at com.google.firebase.database.obfuscated.zzca.zza(com.google.firebase:firebase-database@@16.0.2:63)
       at com.google.firebase.database.obfuscated.zzcd$1.run(com.google.firebase:firebase-database@@16.0.2:55)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
  ```

**Comment by samtstern** [comment] 2018-10-05 17:46
Duplicate of #1291

**Comment by samtstern** [comment] 2018-10-05 17:46
I will take another look at this today, maybe I will be able to see it with a fresh look.

**Closed by samtstern** 2018-10-05 17:46 UTC
