### ISSUE TITLE
IllegalArgumentExceptionUnique transitionNames are required for all sharedElements Raw Text

### ISSUE THREAD

**Issue by clamentsanz** [firebase/FirebaseUI-Android#1041] opened 2017-12-08 14:13 UTC
Hi,

I have this error :

```
Fatal Exception: java.lang.IllegalArgumentExceptionUnique transitionNames are required for all sharedElements Raw Text
--
  | android.support.v4.app.BackStackRecord.addSharedElement (BackStackRecord.java:511)
  | com.firebase.ui.auth.ui.email.RegisterEmailActivity.onNewUser (RegisterEmailActivity.java:127)


```

**Comment by samtstern** [comment] 2017-12-08 16:32
This looks like a duplicate of #1036

**Closed by samtstern** 2017-12-08 16:32 UTC
