### ISSUE TITLE
BUG - FirebaseUI for Auth - InvisibleActivityBase.java line 39 - java.lang.RuntimeException & java.lang.NullPointerException

### ISSUE THREAD

**Issue by postfixNotation** [firebase/FirebaseUI-Android#1826] opened 2020-08-25 11:46 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Nexus 5X
  * Android OS version: 8.1.0
  * Google Play Services version: 4.3.3
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: 6.2.1
  
### Step 3: Describe the problem:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foobar.app/com.firebase.ui.auth.KickoffActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.data.model.FlowParameters.themeId' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.data.model.FlowParameters.themeId' on a null object reference
       at com.firebase.ui.auth.ui.InvisibleActivityBase.onCreate(InvisibleActivityBase.java:39)
       at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:33)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

#### Steps to reproduce:

  This is niether an issue I've experienced myself nor that I've been able to reproduce. But there are Crashlytics reports on a regular basis which are refering to this behavior. The last time this issue has been observed is J**uly 22nd 2020**.
  
#### Observed Results:

  ```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foobar.app/com.firebase.ui.auth.KickoffActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.data.model.FlowParameters.themeId' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.data.model.FlowParameters.themeId' on a null object reference
       at com.firebase.ui.auth.ui.InvisibleActivityBase.onCreate(InvisibleActivityBase.java:39)
       at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:33)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
  
#### Expected Results:

  * I expected to not have this issue.
  
#### Relevant Code:

  * I've not been able to reproduce this bug myself. I'm basically using code as described in the respective docs in this repository.

**Comment by samtstern** [comment] 2020-08-25 14:44
@postfixNotation thanks for all the information.  This is a duplicate of #1650 which has been open for a while but we haven't yet been able to reproduce it or debug it successfully.

**Closed by samtstern** 2020-08-25 14:44 UTC
