### ISSUE TITLE
NPE in InvisibleActivityBase.java line 39 (Firebase UI 7.2.0)

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#1978] opened 2021-07-14 11:25 UTC
### Step 2: Describe your environment

  * Android device: Nexus 5X
  * Android OS version: 8.1.0
  * Google Play Services version: Unknown
  * Firebase/Play Services SDK version: com.google.firebase:firebase-bom:28.2.0
  * FirebaseUI version: 7.2.0
  
### Step 3: Describe the problem:

After updating to version 7.2.0 and releasing the app in production, several users encounter the crash below.

#### Steps to reproduce:

 Not able to reproduce locally, only reported via Crashlytics 

#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

Caused by java.lang.NullPointerException: Attempt to read from field 'int f.e.a.a.i.a.b.P0' on a null object reference
       at com.firebase.ui.auth.ui.InvisibleActivityBase.onCreate(InvisibleActivityBase.java:39)
       at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:36)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  
#### Expected Results:

No NPE from library code.
  
#### Relevant Code:

N/A

**Comment by samtstern** [comment] 2021-07-16 13:57
@peterhav thanks for reporting this one. I think it is a duplicate of https://github.com/firebase/FirebaseUI-Android/issues/1650 (which I see you commented on) although I appreciate that you followed up to let us know it's still happening.

**Closed by samtstern** 2021-07-16 13:57 UTC
