### ISSUE TITLE
AndroidX/Jetpack not working correctly with FirebaseUI

### ISSUE THREAD

**Issue by snotyak** [firebase/FirebaseUI-Android#1348] opened 2018-06-11 00:58 UTC
* Android device: Pixel 2 XL
  * Android OS version: P Preview 3
  * FirebaseUI version: 4.0.1
  
### Step 3: Describe the problem:

FirebaseUI isn't using the latest `ConstraintLayout`. See
https://stackoverflow.com/questions/50774110/androidx-error-inflating-view

#### Steps to reproduce:

1. Use firebase-ui 4.0.1
2. Use jetpack + androidx
3. Use 
```
startActivityForResult(
        AuthUI.getInstance().build (),
        RC_SIGN_IN)
```
4. Verify that you get `Error inflating class androidx.constraintlayout.widget.ConstraintLayout`
5. For some reason this library is using `androidx.constraintlayout.widget.ConstraintLayout` but should be using `androidx.constraintlayout.ConstraintLayout`

#### Observed Results:

```
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2902)
```
  
#### Expected Results:

  * I expect the app to not crash
  
#### Relevant Code:
```
startActivityForResult(
        AuthUI.getInstance()
                .createSignInIntentBuilder()
                .setAvailableProviders(listOf(
                        AuthUI.IdpConfig.EmailBuilder().build(),
                        AuthUI.IdpConfig.GoogleBuilder().build()))
                .build(),
        RC_SIGN_IN)
```

**Comment by krisu7** [comment] 2018-06-11 08:13
@snotyak duplicate of #1346

**Comment by krisu7** [comment] 2018-06-11 08:21
Supporting AndroidX may be a problem since it is in alpha and not everyone is ready to incorporate it into their projects unfortunately. Refactoring tool is only in AS canary too, i think.

**Comment by samtstern** [comment] 2018-06-11 15:28
@krisu7 thanks for chiming in!  Yes you're right on all counts.  We can't adopt AndroidX yet because the libraries/IDE/jetifier/etc are not yet stable.

**Closed by samtstern** 2018-06-11 15:28 UTC

**Comment by elmariocarlos** [comment] 2019-05-28 15:28
And what about now @krisu7  @samtstern ? It's almost been a year and AndroidX is not going away, so maybe time to get some further compatibility?

**Comment by samtstern** [comment] 2019-05-28 16:31
@elmariocarlos thanks for asking!  We have decided to this as soon as the Firebase Android SDKs migrate to depend on AndroidX.  The good news is that should be happening in not too long!

**Comment by elmariocarlos** [comment] 2019-07-10 05:00
Hi, saw Flutter 1.7 moving to AndroidX full compat; so now it would be Firebase Android SDKs turn, but is this something to be looked on here or where should we go consult progress?

**Comment by samtstern** [comment] 2019-07-10 05:30
The Firebase Android SDK moved to AndroidX a few weeks ago.  Moving
FirebaseUI is next!

**Comment by elmariocarlos** [comment] 2019-07-10 05:56
Thanks for the update @samtstern, looking forward to this =)

**Comment by ErstwhileIII** [comment] 2019-08-18 14:35
Any update to a target time for the implementation of Androidx for FirebaseUI?

Who would be working on an additional flutter implementation ot the UI components of FirebaseAuthUI ?

Thanks
