### ISSUE TITLE
Checking... not working 

### ISSUE THREAD

**Issue by mohammedhammouri** [firebase/FirebaseUI-Android#653] opened 2017-03-29 14:55 UTC
* Android device: Huawei m8
  * Android OS version: 6.0
  * Google Play Services version: unknown
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.2.0
  * Smart lock enabled

One user in the app (Zunbarak) is unable to sign in ,using Facebook/Google/Email , after he press on any of them or enters his email the "checking..." dialog appear then nothing happens,other users of the app are not experincing the same problem.
I have sent reset password email , didn't work for his email,
Then I have removed his account from users in firebase console the same result.
Please give me an advice what is the problem?

**Comment by samtstern** [comment] 2017-03-29 15:25
@mohammedhammouri there's not enough information here to debug this.  At minimum I'd need to see the `adb logcat` output from this user while sign in is attempted.  It's also very possible that this user's device is the issue.  It could have a bad network connection, or maybe it has a sideloaded version of Google Play services that's not compatible.

**Comment by mohammedhammouri** [comment] 2017-03-29 21:36
@samtstern I can't reproduce the issue in any of the devices I have , nor I can have a logcat of it.
The user have tried several times in different times, the dialog(checking...) disappears but nothing is showing next.
How can I know in code if he have a "sideloaded version of Google Play services that's not compatible" so I can show an error to update Google play services?

**Comment by samtstern** [comment] 2017-04-07 19:24
@mohammedhammouri sorry if we can't reproduce the issue there's really not much I can do.  Let's close this and we can re-open if anyone finds a way to reproduce this.

I'm not aware of a way to check for sideloaded versions of Play services, I just know that there are many sites out there (like apkmirror) that provided Play services to devices that were never meant to have it which results in bad and unpredictable things.

**Closed by samtstern** 2017-04-07 19:24 UTC
