### ISSUE TITLE
Please don't use beta dependencies in your code

### ISSUE THREAD

**Issue by Chozzle** [firebase/FirebaseUI-Android#1059] opened 2017-12-16 10:40 UTC
The file fui_confirmation_code_layout currently uses <android.support.constraint.Barrier> which is only supported if I have the dependency 'com.android.support.constraint:constraint-layout:1.1.0-beta1' 
This caused me a few hours of frustration

**Comment by SUPERCILEX** [comment] 2017-12-16 18:29
@Chozzle Apologies for the inconvenience, we aren't distributing our dependencies correctly. This will be fixed ASAP.

Duplicate of #1060

**Comment by samtstern** [comment] 2017-12-18 17:28
Thanks @Chozzle.  This is a duplicate of #1060 and we'll fix it ASAP as @SUPERCILEX said.

**Closed by samtstern** 2017-12-18 17:28 UTC
