### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shimiuh** [firebase/FirebaseUI-Android#1050] opened 2017-12-13 13:49 UTC
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

Yes

### Step 2: Describe your environment

smartphone Device
Brand: samsung
Model: Galaxy S3
Orientation: Portrait
RAM free: 651.44 MB
Disk free: 7.74 GB

Operating System
Version: 4.4.4
Orientation: Portrait
Rooted: No

Crash
Date: Dec 12, 2017, 10:30:00 AM

  * Android device: _____ 
  * Android OS version: _____
  * Google Play Services version:  apply plugin: 'com.google.gms.google-services'
  * Firebase/Play Services SDK version:  com.google.firebase:firebase-core:11.4.2'
  * FirebaseUI version: com.firebaseui:firebase-ui-auth:3.1.0 
  
#### Steps to reproduce:
Crash in playstore

Fatal Exception: java.lang.IllegalArgumentException
Unique transitionNames are required for all sharedElements
keyboard_arrow_up
android.support.v4.app.BackStackRecord.addSharedElement (BackStackRecord.java:511)
arrow_right
com.firebase.ui.auth.ui.email.RegisterEmailActivity.onNewUser (RegisterEmailActivity.java:127)
com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess (CheckEmailFragment.java:208)
com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess (CheckEmailFragment.java:204)
com.google.android.gms.tasks.zzj.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:733)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:146)
android.app.ActivityThread.main (ActivityThread.java:5679)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1291)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1107)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by samtstern** [comment] 2017-12-13 18:10
This is a duplicate of #1036

**Closed by samtstern** 2017-12-13 18:10 UTC
