### ISSUE TITLE
error in com.firebase.ui.auth.ui.email.SignInActivity 

### ISSUE THREAD

**Issue by mrhuythien** [firebase/FirebaseUI-Android#196] opened 2016-06-21 07:20 UTC
I got this error in Samsung galaxy GT-S7580 (Android 4.2.2) 

FATAL EXCEPTION: main
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.****.****/com.firebase.ui.auth.ui.email.SignInActivity}: android.view.InflateException: Binary XML file line #65: Error inflating class Button
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
                                                                                   at android.app.ActivityThread.access$700(ActivityThread.java:157)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                   at android.os.Looper.loop(Looper.java:176)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5317)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: android.view.InflateException: Binary XML file line #65: Error inflating class Button
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                   at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:56)
                                                                                   at android.app.Activity.performCreate(Activity.java:5326)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309) 
                                                                                   at android.app.ActivityThread.access$700(ActivityThread.java:157) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                   at android.os.Looper.loop(Looper.java:176) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5317) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: android.content.res.Resources$NotFoundException: File res/drawable/rounded_button.xml from drawable resource ID #0x7f0200c3
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2842)
                                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                                   at android.view.View.<init>(View.java:3529)
                                                                                   at android.widget.TextView.<init>(TextView.java:847)
                                                                                   at android.widget.Button.<init>(Button.java:126)
                                                                                   at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
                                                                                   at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
                                                                                   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
                                                                                   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:760) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                   at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:56) 
                                                                                   at android.app.Activity.performCreate(Activity.java:5326) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309) 
                                                                                   at android.app.ActivityThread.access$700(ActivityThread.java:157) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                   at android.os.Looper.loop(Looper.java:176) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5317) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                   at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                                   at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:967)
                                                                                   at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:921)
                                                                                   at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:183)
                                                                                   at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:921)
                                                                                   at android.graphics.drawable.Drawable.createFromXml(Drawable.java:858)
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2839)
                                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                                   at android.view.View.<init>(View.java:3529) 
                                                                                   at android.widget.TextView.<init>(TextView.java:847) 
                                                                                   at android.widget.Button.<init>(Button.java:126) 
                                                                                   at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62) 
                                                                                   at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58) 
                                                                                   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039) 
                                                                                   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:760) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                   at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:56) 
                                                                                   at android.app.Activity.performCreate(Activity.java:5326) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309) 
                                                                                   at android.app.ActivityThread.access$700(ActivityThread.java:157) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                   at android.os.Looper.loop(Looper.java:176) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5317) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 

Please check it

**Comment by akitikkx** [comment] 2016-06-29 07:10
Also getting the same issue when trying to sign in with email. The above error occurs when the user clicks on the Sign in with Email > "None of the above" link. This seems to have started happening after the auth-ui update to Android 24

**Comment by samtstern** [comment] 2016-08-16 17:04
I think this is a duplicate of #145 which was fixed by Pull Requesr #226.  Closing this issue, version `0.4.4` of the library should fix this for you.

**Closed by samtstern** 2016-08-16 17:04 UTC
Labels: feature:auth
