### ISSUE TITLE
Styling Phone Auth FirebaseUI Show Animation

### ISSUE THREAD

**Issue by willemevenwel** [firebase/FirebaseUI-Android#766] opened 2017-06-20 13:59 UTC
This is not a bug.

I've been googling for a bit and cant find the answer.

Using 
```
startActivityForResult(
           AuthUI.getInstance().createSignInIntentBuilder()
           // ...
```

to prompt the user to login via specified provider.

However when the user selects Sign in with phone, the animation of the view which kinda slides up to prompt the user to fill in phone number is not consistent with the rest of the animation in my application. 

I want to know if it is possible to changes this?

**Comment by willemevenwel** [comment] 2017-06-21 10:02
The way I animate showing the Firebase SignInIntent:
ActivityOptions options = ActivityOptions.makeCustomAnimation(getApplicationContext(), R.anim.trans_left_in, R.anim.trans_left_out);
startActivityForResult(
                        AuthUI.getInstance()
                         ...                                
                        .build()
        ,RC_SIGN_IN
        ,options.toBundle()
);

So you will see in the attachment the signin navigates nicely from the welcome screen to showing.

However the phone auth view pops up from the bottom in a not so pretty way.

Hope this information helps, your help will be appreciated.

![ezgif-1-9671da91fe](https://user-images.githubusercontent.com/13721310/27378859-7b3141cc-5679-11e7-8420-0c0919b3fa4a.gif)

**Comment by samtstern** [comment] 2017-06-21 16:10
Ah I see the request is to be able to control the animation between screens in FirebaseUI for auth.  You're right we don't support that now, this goes in the bucket of "allow advanced customization" which may improve in the future.

**Comment by samtstern** [comment] 2017-06-21 16:10
Going to close this as a duplicate of #229 and I will add a note in there.

**Closed by samtstern** 2017-06-21 16:10 UTC
